import Erdos1084.Phase1BoundaryMeasure

#print axioms Erdos1084.UnitSeparatedConfiguration.measure_frontier_le_sum_exposedPatch

#check Erdos1084.UnitSeparatedConfiguration.measure_frontier_le_sum_exposedPatch
