"""Generate the exhaustive AFP R8 Lean signature and axiom audit.

The generator deliberately audits declarations syntactically owned by the
project.  It emits both ``#check`` (signature inspection) and ``#print axioms``
for every public theorem/lemma in every non-audit AFPBarrier module.
"""

from __future__ import annotations

import json
import re
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
LEAN_ROOT = PROJECT_ROOT / "AFPBarrier"
RELEASE_ROOT = PROJECT_ROOT / "release"
OUTPUT_LEAN = LEAN_ROOT / "ReleaseAxiomAudit.lean"
OUTPUT_INDEX = RELEASE_ROOT / "LEAN_DECLARATION_INDEX.json"
EXPECTED_DECLARATIONS = 512

EXCLUDED_MODULES = {
    "AxiomAudit.lean",
    "Gate5AxiomAudit.lean",
    "Gate6AxiomAudit.lean",
    "P2BAxiomAudit.lean",
    "P2DAccelerationAxiomAudit.lean",
    "PureMathAxiomAudit.lean",
    "ReleaseAxiomAudit.lean",
}

DECLARATION = re.compile(
    r"^\s*(?:@\[[^]]+\]\s*)*(?:protected\s+)?"
    r"(?P<kind>theorem|lemma)\s+(?P<name>[A-Za-z0-9_'.]+)"
)


def collect() -> tuple[list[Path], list[dict[str, object]]]:
    modules = sorted(
        path
        for path in LEAN_ROOT.glob("*.lean")
        if path.name not in EXCLUDED_MODULES
    )
    declarations: list[dict[str, object]] = []
    for path in modules:
        text = path.read_text(encoding="utf-8")
        if "namespace AFPBarrier" not in text:
            raise RuntimeError(f"unexpected namespace boundary: {path}")
        for line_number, line in enumerate(text.splitlines(), start=1):
            match = DECLARATION.match(line)
            if match:
                declarations.append(
                    {
                        "name": f"AFPBarrier.{match.group('name')}",
                        "kind": match.group("kind"),
                        "file": path.relative_to(PROJECT_ROOT).as_posix(),
                        "line": line_number,
                    }
                )

    names = [str(row["name"]) for row in declarations]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise RuntimeError(f"duplicate declaration names: {duplicates}")
    if len(declarations) != EXPECTED_DECLARATIONS:
        raise RuntimeError(
            f"release declaration count changed: {len(declarations)} != "
            f"{EXPECTED_DECLARATIONS}; inspect and update the gate deliberately"
        )
    return modules, declarations


def render_lean(modules: list[Path], declarations: list[dict[str, object]]) -> str:
    lines = [f"import AFPBarrier.{module.stem}" for module in modules]
    lines.extend([
        "",
        "/-! AFP R8 exhaustive generated signature and axiom audit.",
        "",
        "Generated by `release/tools/generate_lean_release_audit.py`.",
        "Do not hand-edit. Every public project theorem/lemma receives both",
        "`#check` and `#print axioms`; analytic manuscript arguments remain",
        "outside this finite formal surface.",
        "-/",
        "",
        f"/-! {len(declarations)} declarations. -/",
        "",
    ])
    for row in declarations:
        name = row["name"]
        lines.append(f"-- {row['file']}:{row['line']}")
        lines.append(f"#check {name}")
        lines.append(f"#print axioms {name}")
    return "\n".join(lines) + "\n"


def main() -> None:
    modules, declarations = collect()
    OUTPUT_LEAN.write_text(
        render_lean(modules, declarations), encoding="utf-8", newline="\n"
    )
    payload = {
        "schema": "afp-r8-lean-declaration-index-v1",
        "declaration_count": len(declarations),
        "module_count": len(modules),
        "generated_lean": OUTPUT_LEAN.relative_to(PROJECT_ROOT).as_posix(),
        "classification": (
            "finite project theorem/lemma signatures and axiom dependencies only; "
            "not whole-paper formalization"
        ),
        "declarations": declarations,
    }
    OUTPUT_INDEX.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"generated {len(declarations)} declarations from {len(modules)} modules")


if __name__ == "__main__":
    main()
