import Mathlib

namespace Erdos1084

/-!
# Closed dense equivalence classes in a topological group

This module formalizes the logical closure step in the coherent-twin quotient
audit.  The geometric theorem that two FCC twin generators generate a dense
subgroup of `SO(3)` remains an ordinary Lie-group theorem.  Once density is
supplied, the collapse of any closed left-invariant equivalence relation is
proved here without additional assumptions.
-/

section IdentityClass

variable {G : Type*} [Group G]

/-- The equivalence class of the identity. -/
def relIdentityClass (r : G → G → Prop) : Set G := {g | r 1 g}

/--
For a left-invariant equivalence relation on a group, the identity class is a
subgroup.
-/
def relIdentitySubgroup
    (r : G → G → Prop)
    (hrefl : Reflexive r)
    (hsymm : Symmetric r)
    (htrans : Transitive r)
    (hleft : ∀ q {a b : G}, r a b → r (q * a) (q * b)) : Subgroup G where
  carrier := relIdentityClass r
  one_mem' := hrefl 1
  mul_mem' := by
    intro a b ha hb
    have hab : r a (a * b) := by
      simpa using hleft a hb
    exact htrans ha hab
  inv_mem' := by
    intro a ha
    have hback : r a⁻¹ 1 := by
      simpa using hleft a⁻¹ ha
    exact hsymm hback

@[simp] theorem mem_relIdentitySubgroup
    (r : G → G → Prop)
    (hrefl : Reflexive r)
    (hsymm : Symmetric r)
    (htrans : Transitive r)
    (hleft : ∀ q {a b : G}, r a b → r (q * a) (q * b))
    (g : G) :
    g ∈ relIdentitySubgroup r hrefl hsymm htrans hleft ↔ r 1 g :=
  Iff.rfl

end IdentityClass

section ClosedDense

variable {G : Type*} [Group G] [TopologicalSpace G]

/--
A closed dense identity class of a left-invariant relation contains every group
element, so the relation is universal.
-/
theorem relation_universal_of_closed_dense_identityClass
    (r : G → G → Prop)
    (hleft : ∀ q {a b : G}, r a b → r (q * a) (q * b))
    (hclosed : IsClosed (relIdentityClass r))
    (hdense : Dense (relIdentityClass r)) :
    ∀ a b : G, r a b := by
  intro a b
  have habClass : a⁻¹ * b ∈ relIdentityClass r := by
    have hclosure := hdense (a⁻¹ * b)
    rw [hclosed.closure_eq] at hclosure
    exact hclosure
  have hab : r 1 (a⁻¹ * b) := habClass
  have htranslated := hleft a hab
  simpa [mul_assoc] using htranslated

/--
It is enough that the identity class contain a dense subgroup.  This is the form
used after proving density of the subgroup generated by coherent twin rotations.
-/
theorem relation_universal_of_closed_dense_subgroup
    (r : G → G → Prop)
    (hleft : ∀ q {a b : G}, r a b → r (q * a) (q * b))
    (hclosed : IsClosed (relIdentityClass r))
    (H : Subgroup G)
    (hHdense : Dense (H : Set G))
    (hHrel : ∀ g : G, g ∈ H → r 1 g) :
    ∀ a b : G, r a b := by
  apply relation_universal_of_closed_dense_identityClass r hleft hclosed
  intro g
  have hgH : g ∈ closure (H : Set G) := hHdense g
  have hmono : closure (H : Set G) ⊆ closure (relIdentityClass r) :=
    closure_mono hHrel
  exact hmono hgH

/--
Full equivalence-relation form: the identity class is automatically a subgroup,
and if that subgroup is closed and dense, every two elements are equivalent.
-/
theorem equivalence_universal_of_closed_dense_identitySubgroup
    (r : G → G → Prop)
    (hrefl : Reflexive r)
    (hsymm : Symmetric r)
    (htrans : Transitive r)
    (hleft : ∀ q {a b : G}, r a b → r (q * a) (q * b))
    (hclosed : IsClosed
      ((relIdentitySubgroup r hrefl hsymm htrans hleft : Subgroup G) : Set G))
    (hdense : Dense
      ((relIdentitySubgroup r hrefl hsymm htrans hleft : Subgroup G) : Set G)) :
    ∀ a b : G, r a b := by
  change IsClosed (relIdentityClass r) at hclosed
  change Dense (relIdentityClass r) at hdense
  exact relation_universal_of_closed_dense_identityClass r hleft hclosed hdense

end ClosedDense

end Erdos1084
