"""Positive quadrature, angular graph, transfer, adaptivity, and S_N tools."""

__version__ = "0.6.0"

from .adaptive_sn2d import (
    AdaptiveSN2DIteration,
    AdaptiveSN2DResult,
    SN2DGoalIndicator,
    run_adaptive_sn2d,
    sn2d_goal_indicator,
)
from .adaptivity import (
    AdaptationResult,
    HysteresisMarker,
    IndicatorResult,
    adapt_positive_quadrature,
    contributon_smoothness_indicator,
    dual_weighted_indicator,
    filtered_harmonic_bootstrap,
    graph_heat_bootstrap,
    local_tangent_children,
)

from .global_quadrature import (
    FixedPoolMinimumCertificate,
    NodeCountCertificate,
    VariableNodeQuadratureResult,
    candidate_pool_minimum_certificate,
    harmonic_gram_lower_bound,
    minimum_separation,
    node_count_certificate,
    regular_tetrahedron_rule,
    variable_node_positive_quadrature,
)
from .graph_convergence import (
    GraphConvergenceCertificate,
    HarmonicConsistencyRecord,
    SphericalGridQuality,
    certify_graph_family,
    graph_family_records,
    spherical_grid_quality,
)
from .sn3d import (
    BoundaryData3D,
    CartesianGrid3D,
    SN3DProblem,
    SN3DSolution,
    assemble_system as assemble_system_3d,
    axis_quadrature_sphere,
    compute_responses as compute_responses_3d,
    execution_plan as execution_plan_3d,
    flux_sha256 as flux_sha256_3d,
    forward_adjoint_identity as forward_adjoint_identity_3d,
    global_particle_balance as global_particle_balance_3d,
    response_vector as response_vector_3d,
    solve_direct as solve_direct_3d,
    solve_discrete_adjoint as solve_discrete_adjoint_3d,
    solve_source_iteration as solve_source_iteration_3d,
)

from .graph_generator import (
    GraphConnectivityDiagnostics,
    GraphGenerator,
    conductance_exactness_certificate,
    fit_graph_generator,
)
from .io import (
    load_graph_hdf5,
    load_quadrature_hdf5,
    save_graph_hdf5,
    save_quadrature_hdf5,
)
from .quadrature import (
    FarkasCertificate,
    MinimumResidualResult,
    MomentFitResult,
    PositiveQuadrature,
    ResponseMomentCertificate,
    balanced_multiresponse_density,
    caratheodory_support_reduction,
    exact_surface_harmonic_moments,
    farkas_infeasibility_certificate,
    fibonacci_sphere,
    finite_pool_positive_quadrature,
    finite_pool_symmetric_quadrature,
    gauss_legendre_product_sphere,
    minimum_node_positive_quadrature,
    minimum_residual_positive_weights,
    moment_conditioning,
    node_count_bounds,
    nonlinear_refine_quadrature,
    real_spherical_harmonics,
    response_error_from_moment_residual,
)
from .sn2d import (
    BoundaryData2D,
    CartesianGrid2D,
    SN2DProblem,
    SN2DSolution,
    assemble_system,
    circle_quadrature,
    compute_responses,
    forward_adjoint_identity,
    global_particle_balance,
    response_vector,
    solve_direct,
    solve_discrete_adjoint,
    solve_source_iteration,
)
from .transfer import (
    StateRemapResult,
    TransferDiagnostics,
    TransferResult,
    apply_angular_transfer,
    compose_transfers,
    current_preserving_no_go,
    mass_exact_near_transfer,
    minimum_residual_positive_transfer,
    moment_matrix,
    repeated_transfer_error_bound,
    state_specific_positive_remap,
    transfer_chain_error_bound,
    transfer_diagnostics,
    universal_positive_transfer,
)

__all__ = [
    "AdaptationResult",
    "AdaptiveSN2DIteration",
    "AdaptiveSN2DResult",
    "BoundaryData2D",
    "CartesianGrid2D",
    "FarkasCertificate",
    "GraphConnectivityDiagnostics",
    "GraphGenerator",
    "HysteresisMarker",
    "IndicatorResult",
    "MinimumResidualResult",
    "MomentFitResult",
    "PositiveQuadrature",
    "ResponseMomentCertificate",
    "SN2DGoalIndicator",
    "SN2DProblem",
    "SN2DSolution",
    "StateRemapResult",
    "TransferDiagnostics",
    "TransferResult",
    "adapt_positive_quadrature",
    "apply_angular_transfer",
    "assemble_system",
    "balanced_multiresponse_density",
    "caratheodory_support_reduction",
    "circle_quadrature",
    "compose_transfers",
    "compute_responses",
    "conductance_exactness_certificate",
    "contributon_smoothness_indicator",
    "current_preserving_no_go",
    "dual_weighted_indicator",
    "exact_surface_harmonic_moments",
    "farkas_infeasibility_certificate",
    "fibonacci_sphere",
    "filtered_harmonic_bootstrap",
    "finite_pool_positive_quadrature",
    "finite_pool_symmetric_quadrature",
    "fit_graph_generator",
    "forward_adjoint_identity",
    "gauss_legendre_product_sphere",
    "global_particle_balance",
    "graph_heat_bootstrap",
    "load_graph_hdf5",
    "load_quadrature_hdf5",
    "local_tangent_children",
    "mass_exact_near_transfer",
    "minimum_node_positive_quadrature",
    "minimum_residual_positive_transfer",
    "minimum_residual_positive_weights",
    "moment_conditioning",
    "moment_matrix",
    "node_count_bounds",
    "nonlinear_refine_quadrature",
    "real_spherical_harmonics",
    "repeated_transfer_error_bound",
    "response_error_from_moment_residual",
    "response_vector",
    "run_adaptive_sn2d",
    "save_graph_hdf5",
    "save_quadrature_hdf5",
    "sn2d_goal_indicator",
    "solve_direct",
    "solve_discrete_adjoint",
    "solve_source_iteration",
    "state_specific_positive_remap",
    "transfer_chain_error_bound",
    "transfer_diagnostics",
    "universal_positive_transfer",
    "BoundaryData3D",
    "CartesianGrid3D",
    "FixedPoolMinimumCertificate",
    "GraphConvergenceCertificate",
    "HarmonicConsistencyRecord",
    "NodeCountCertificate",
    "SN3DProblem",
    "SN3DSolution",
    "SphericalGridQuality",
    "VariableNodeQuadratureResult",
    "assemble_system_3d",
    "axis_quadrature_sphere",
    "candidate_pool_minimum_certificate",
    "certify_graph_family",
    "compute_responses_3d",
    "execution_plan_3d",
    "flux_sha256_3d",
    "forward_adjoint_identity_3d",
    "global_particle_balance_3d",
    "graph_family_records",
    "harmonic_gram_lower_bound",
    "minimum_separation",
    "node_count_certificate",
    "regular_tetrahedron_rule",
    "response_vector_3d",
    "solve_direct_3d",
    "solve_discrete_adjoint_3d",
    "solve_source_iteration_3d",
    "spherical_grid_quality",
    "variable_node_positive_quadrature",
]
