"""P2D fixed-point-preserving acceleration and transport-audit primitives."""

from .core import (
    FieldOfValuesReport,
    IterationResult,
    ShellContraction,
    SlowSubspaceReport,
    SpectralEquivalenceReport,
    TransportMismatchReport,
    constrained_defect_correction,
    constrained_error_propagation_operator,
    constrained_low_inverse,
    defect_correction,
    error_propagation_operator,
    field_of_values_bound,
    invariant_residuals,
    iteration_count_bound,
    perturbation_contraction_bound,
    preconditioned_gmres,
    shellwise_contraction,
    slow_subspace_report,
    spectral_equivalence_bound,
    transport_mismatch_decomposition,
)
from .transport import (
    audit_generator,
    complete_transport_audit,
    forward_peaked_sweep,
    higher_shell_adversary,
    load_generators,
    multigroup_boundary_case,
    ray_dominated_adversary,
)

__all__ = [
    "FieldOfValuesReport",
    "IterationResult",
    "ShellContraction",
    "SlowSubspaceReport",
    "SpectralEquivalenceReport",
    "TransportMismatchReport",
    "audit_generator",
    "complete_transport_audit",
    "constrained_defect_correction",
    "constrained_error_propagation_operator",
    "constrained_low_inverse",
    "defect_correction",
    "error_propagation_operator",
    "field_of_values_bound",
    "forward_peaked_sweep",
    "higher_shell_adversary",
    "invariant_residuals",
    "iteration_count_bound",
    "load_generators",
    "multigroup_boundary_case",
    "perturbation_contraction_bound",
    "preconditioned_gmres",
    "ray_dominated_adversary",
    "shellwise_contraction",
    "slow_subspace_report",
    "spectral_equivalence_bound",
    "transport_mismatch_decomposition",
]
