import PlanarContactNumber

#print axioms PlanarContactNumber.contactNumber_le_square
#print axioms PlanarContactNumber.realized_le_f₂
#print axioms PlanarContactNumber.floor_harborthReal_shellN
#print axioms PlanarContactNumber.floor_harborthReal_partial
#print axioms PlanarContactNumber.floor_harborthReal_eq_shellCandidateZ
#print axioms PlanarContactNumber.triangularPoint_dist_sq
#print axioms PlanarContactNumber.one_le_dist_triangularPoint
#print axioms PlanarContactNumber.triangularPoint_injective
#print axioms PlanarContactNumber.triangularPoint_contact_iff
#print axioms PlanarContactNumber.harborthReal_add_le
#print axioms PlanarContactNumber.harborthReal_cut_le
#print axioms PlanarContactNumber.interior_induction_closure
#print axioms PlanarContactNumber.boundary_only_closure
