import AFPBarrier.LocalSphericalFeasibility
import AFPBarrier.ExactLocalRows
import AFPBarrier.QuantitativeExactLocal
import AFPBarrier.AntipodalFeasibility
import AFPBarrier.SphericalFeasibilityAlgebra
import AFPBarrier.QuantitativeSphericalFeasibility
import AFPBarrier.GlobalLossRigidity
import AFPBarrier.SharedEdgeEquilibrium
import AFPBarrier.GroupAveraging
import AFPBarrier.GlobalSharedEdgeDuality
import AFPBarrier.SpectralProductAlgebra
import AFPBarrier.QuadraticCovariance
import AFPBarrier.QuadraticSampling
import AFPBarrier.QuadraticSphereResidual
import AFPBarrier.OneShellQuadraticRigidity
import AFPBarrier.SpectralSamplingObstruction
import AFPBarrier.SphericalQEqualityRigidity
import AFPBarrier.QuantitativeGlobalNearRigidity
import AFPBarrier.QEqualityCovariance

/-! Focused axiom audit for the pure-mathematics branch. -/

#print axioms AFPBarrier.scaledSphericalRowRate_nonneg
#print axioms AFPBarrier.scaledSphericalRowRate_pos
#print axioms AFPBarrier.scaledSphericalRowRate_tangent_balance
#print axioms AFPBarrier.scaledSphericalRowRate_normal_balance
#print axioms AFPBarrier.tangentDependenceWeight_nonneg
#print axioms AFPBarrier.tangentDependenceWeight_balance
#print axioms AFPBarrier.tangentDependenceWeight_normal_scale
#print axioms AFPBarrier.normalizedAngularScale_pos
#print axioms AFPBarrier.exactLocalRowRate_normal_balance
#print axioms AFPBarrier.exactLocalRowRate_sum
#print axioms AFPBarrier.exactLocalRowRate_recover
#print axioms AFPBarrier.normalizedWeightedSum_bounds
#print axioms AFPBarrier.exactLocalRowRate_sum_bounds
#print axioms AFPBarrier.uniformDependenceMixture_sum
#print axioms AFPBarrier.uniformDependenceMixture_lower
#print axioms AFPBarrier.exactLocalRowRate_twoFactor_bounds
#print axioms AFPBarrier.antipodalOnlyFeasible_iff_simplex
#print axioms AFPBarrier.uniformAntipodalRate_strictly_feasible
#print axioms AFPBarrier.mixedRow_from_tangentBudget
#print axioms AFPBarrier.mixedRow_to_tangentBudget
#print axioms AFPBarrier.mixedRow_tangentNormalBudget_bounds
#print axioms AFPBarrier.mixedRowFeasible_iff_exists_tangentParameter
#print axioms AFPBarrier.tangentNormalScale_pos
#print axioms AFPBarrier.normalBalance_outgoingRate_lower
#print axioms AFPBarrier.normalBalance_outgoingRate_upper
#print axioms AFPBarrier.sharedEdge_equilibrium_implies_weightedCentering
#print axioms AFPBarrier.squareLocalRate_coordinate_exact
#print axioms AFPBarrier.squareDual_transpose_zero
#print axioms AFPBarrier.squareDual_work
#print axioms AFPBarrier.square_sharedEdge_infeasible
#print axioms AFPBarrier.coordinateBalance_averagedConductance
#print axioms AFPBarrier.groupOrbitAverage_reconciliation
#print axioms AFPBarrier.groupOrbitAverage_reconciliation_of_edgeRepresentative
#print axioms AFPBarrier.sharedEdgeDualWork_radial
#print axioms AFPBarrier.positiveLP_complementarySlackness
#print axioms AFPBarrier.jumpGenerator_product_identity
#print axioms AFPBarrier.spectralProduct_arbitraryTarget
#print axioms AFPBarrier.spectralProduct_resonance_iff
#print axioms AFPBarrier.spectralSquare_resonance_iff
#print axioms AFPBarrier.jumpGenerator_sampledQuadratic
#print axioms AFPBarrier.sampledQuadratic_arbitraryTarget
#print axioms AFPBarrier.sampledQuadratic_eigen_iff
#print axioms AFPBarrier.samplingKernel_subset_formExact
#print axioms AFPBarrier.sampledExact_iff_range_inter_targetKernel
#print axioms AFPBarrier.linear_samplingKernel_le_residualKernel
#print axioms AFPBarrier.linearSampledResidual_finrank_le_sampling
#print axioms AFPBarrier.weighted_sum_jumpGenerator_eq_zero_of_detailedBalance
#print axioms AFPBarrier.detailedBalance_eigen_implies_weightedMean_zero
#print axioms AFPBarrier.sampledQuadratic_center_eq_weightedMean
#print axioms AFPBarrier.sampledQuadratic_zeroTarget_center_independent
#print axioms AFPBarrier.linearSampledExactRange_eq_range_inf_targetKernel
#print axioms AFPBarrier.linearSampledExactRange_finrank_eq_formExact_sub_samplingKernel
#print axioms AFPBarrier.linearSampledExactRange_finrank_eq_samplingRank_sub_residualRank
#print axioms AFPBarrier.matrixFrobeniusPairing_eq_trace_mul_of_isSymm_right
#print axioms AFPBarrier.trace_sphereResidualMatrix_eq_zero
#print axioms AFPBarrier.sphereResidualMatrix_isSymm
#print axioms AFPBarrier.sphereResidual_factorization
#print axioms AFPBarrier.matrixFrobeniusPairing_sphereResidualMatrix_eq_trace
#print axioms AFPBarrier.sphereResidual_factorization_trace
#print axioms AFPBarrier.sphereFormExact_eq_residualOrthogonal
#print axioms AFPBarrier.sphereSamplingKernel_le_formExact
#print axioms AFPBarrier.sphereSampledExact_eq_range_inf_targetKernel
#print axioms AFPBarrier.sphereSampledExact_finrank_eq_form_sub_alias
#print axioms AFPBarrier.sphereSampledExact_finrank_eq_samplingRank_sub_residualRank
#print axioms AFPBarrier.oneShell_radial_rate
#print axioms AFPBarrier.oneShell_tangent_balance
#print axioms AFPBarrier.oneShell_covariance_decomposition
#print axioms AFPBarrier.oneShell_actual_covariance_decomposition
#print axioms AFPBarrier.oneShell_traceFree_residual_pairing
#print axioms AFPBarrier.oneShell_sphereResidual_row
#print axioms AFPBarrier.oneShell_sphereResidual_factorization
#print axioms AFPBarrier.oneShell_sphereResidualKernel_eq_samplingKernel
#print axioms AFPBarrier.oneShell_sphereResidualRank_eq_samplingRank
#print axioms AFPBarrier.oneShell_sphereSampledExactRange_eq_bot
#print axioms AFPBarrier.spectralSampledSpaces_iSupIndep
#print axioms AFPBarrier.spectralSampledSpaces_pairwise_disjoint
#print axioms AFPBarrier.spectralSampledSpaces_finrank_sum_le
#print axioms AFPBarrier.spectralSampledFunctions_finrank_sum_le
#print axioms AFPBarrier.sphericalEigenvalue_injective
#print axioms AFPBarrier.harmonicSampledSpaces_iSupIndep
#print axioms AFPBarrier.sphericalEigenvalue_dimension_one_collision
#print axioms AFPBarrier.sphericalEigenvalue_dimension_one_not_injective
#print axioms AFPBarrier.internalScalarOperator_apply_of_mem
#print axioms AFPBarrier.internalScalarOperator_constants_eq_zero

#print axioms AFPBarrier.rate_eq_of_symmetric_active_loss
#print axioms AFPBarrier.rate_eq_of_active_reflTransGen
#print axioms AFPBarrier.connected_active_loss_rigidity

/-! Prompt 3: exact spherical equality and global propagation. -/

#print axioms AFPBarrier.sphericalChordLoss_symmetric
#print axioms AFPBarrier.jumpGenerator_sphericalPairing
#print axioms AFPBarrier.coordinateEigenmap_lossMoment_two
#print axioms AFPBarrier.normalizedOmega_barycenter_of_coordinateEigenmap
#print axioms AFPBarrier.jumpRate_pos_of_lossMoment_two
#print axioms AFPBarrier.normalizedEdgeWeight_sum_one
#print axioms AFPBarrier.normalizedLossScale_mean_one
#print axioms AFPBarrier.normalizedLossScale_secondMoment
#print axioms AFPBarrier.weightedSecondMoment_sub_one_eq_variance
#print axioms AFPBarrier.sphericalQ_sub_one_eq_normalizedLossVariance
#print axioms AFPBarrier.one_le_sphericalQAt
#print axioms AFPBarrier.sphericalQ_eq_one_active_loss
#print axioms AFPBarrier.active_symmetric_of_shared_conductance
#print axioms AFPBarrier.connected_spherical_active_loss_rigidity
#print axioms AFPBarrier.finite_spherical_qOne_global_rigidity

/-! Prompt 3: explicit graph-global near-rigidity. -/

#print axioms AFPBarrier.abs_sub_one_le_of_sq_le_delta_sq
#print axioms AFPBarrier.pointwise_delta_bound
#print axioms AFPBarrier.sphericalQ_pointwise_delta_bound
#print axioms AFPBarrier.normalized_scale_interval_of_abs
#print axioms AFPBarrier.normalized_scale_qDelta_cross_bounds
#print axioms AFPBarrier.one_le_qDelta
#print axioms AFPBarrier.adjacent_rate_cross_bounds
#print axioms AFPBarrier.adjacent_rate_ratio_bounds
#print axioms AFPBarrier.adjacent_rate_relative_error_bound
#print axioms AFPBarrier.adjacent_rate_qDelta_cross_bounds
#print axioms AFPBarrier.incident_loss_cross_bounds
#print axioms AFPBarrier.incident_loss_ratio_bounds
#print axioms AFPBarrier.path_rate_cross_bounds
#print axioms AFPBarrier.path_rate_ratio_bounds
#print axioms AFPBarrier.path_loss_ratio_bounds
#print axioms AFPBarrier.abs_log_rate_sub_le_of_cross_bounds
#print axioms AFPBarrier.adjacent_log_rate_bound
#print axioms AFPBarrier.path_log_rate_bound
#print axioms AFPBarrier.abs_log_normalized_scale_le_hDelta
#print axioms AFPBarrier.reference_loss_log_bound
#print axioms AFPBarrier.diameter_log_rate_bound
#print axioms AFPBarrier.pow_le_pow_of_one_le_of_nat_le
#print axioms AFPBarrier.diameter_rate_ratio_bounds
#print axioms AFPBarrier.radial_covariance_error_bounds

/-! Prompt 3: covariance and anisotropy boundary. -/

#print axioms AFPBarrier.covarianceTrace_eq_four_of_normLoss
#print axioms AFPBarrier.radialCovariance_eq_sphericalEpsilon
#print axioms AFPBarrier.sphericalEpsilon_eq_four_mul_Q_div_rate
#print axioms AFPBarrier.normalizedTangent_centered_of_barycenter
#print axioms AFPBarrier.normalizedTangentSecondMoment_trace_one
#print axioms AFPBarrier.weighted_centered_affine_product_sum
#print axioms AFPBarrier.qOne_covarianceEntry_decomposition
#print axioms AFPBarrier.jumpCovariance_eq_rate_mul_normalized
#print axioms AFPBarrier.qOne_jumpCovariance_decomposition
#print axioms AFPBarrier.qOne_covariance_axial_iff_tangentHalf
#print axioms AFPBarrier.oneShellSecondMoment_eq_rate_mul_normalized
#print axioms AFPBarrier.normalizedTangentHalf_iff_d3_oneShellSecondMoment
#print axioms AFPBarrier.qOne_residual_entry_algebra
#print axioms AFPBarrier.sphereResidualMatrix_entry_of_trace_six
#print axioms AFPBarrier.qOne_sphereResidual_entry_decomposition
#print axioms AFPBarrier.weightedOctahedron_axis_axial_iff
#print axioms AFPBarrier.weightedOctahedron_all_axes_axial_iff
