import Mathlib.Tactic

/-!
# Stable finite algebra for P2C quadrature--generator co-design

This module formalizes only finite identities that are independent of the
floating solver and of the analytic outer-convergence machinery.  It covers

* the dense positive conductance initializer on a normalized quadrature;
* its exact action on centered sampled functions, including H1 coordinates;
* zero extension when a permitted edge set is enlarged;
* the algebraic descent consequence of an exact proximal comparison; and
* the Paper-I lower/rate constant product used by the P2C all-orders sandwich.

It deliberately does not formalize general SDP strong duality, Berge or
Robinson theorems, limiting subdifferentials, Riemannian optimization, or the
analytic P1E construction.
-/

open scoped BigOperators

namespace AFPBarrier

variable {I E K R : Type*}
  [Fintype I] [DecidableEq I]
  [Fintype E] [DecidableEq E]
  [Fintype K] [DecidableEq K]
  [Fintype R] [DecidableEq R]

/-- Complete-graph conductance associated with a normalized positive mass. -/
def denseCodesignConductance
    (lambda : ℝ) (w : I → ℝ) (i j : I) : ℝ :=
  lambda * w i * w j

/-- Positive target rate and positive quadrature masses give strictly positive
complete-graph conductances. -/
theorem denseCodesignConductance_pos
    (lambda : ℝ) (w : I → ℝ)
    (hlambda : 0 < lambda) (hw : ∀ i, 0 < w i) (i j : I) :
    0 < denseCodesignConductance lambda w i j := by
  unfold denseCodesignConductance
  exact mul_pos (mul_pos hlambda (hw i)) (hw j)

/-- The finite action generated by `lambda * w_i * w_j` after division by the
row mass.  Writing it directly avoids any convention about diagonal edges. -/
def denseCodesignAction
    (lambda : ℝ) (w f : I → ℝ) (i : I) : ℝ :=
  lambda * ∑ j, w j * (f j - f i)

/-- Under total mass one, the dense action is target rate times weighted mean
minus the point value. -/
theorem denseCodesignAction_mass_one
    (lambda : ℝ) (w f : I → ℝ) (i : I)
    (hmass : ∑ j, w j = 1) :
    denseCodesignAction lambda w f i =
      lambda * ((∑ j, w j * f j) - f i) := by
  classical
  unfold denseCodesignAction
  simp_rw [mul_sub]
  rw [Finset.sum_sub_distrib, Finset.sum_mul, hmass]
  ring

/-- Constants are reproduced exactly by the dense initializer. -/
theorem denseCodesignAction_constant
    (lambda : ℝ) (w : I → ℝ) (c : ℝ) (i : I) :
    denseCodesignAction lambda w (fun _ => c) i = 0 := by
  classical
  simp [denseCodesignAction]

/-- Every centered sampled function is an exact eigenvector with eigenvalue
`-lambda`; coordinate centering therefore gives exact H1 action. -/
theorem denseCodesignAction_centered
    (lambda : ℝ) (w f : I → ℝ) (i : I)
    (hmass : ∑ j, w j = 1)
    (hcenter : ∑ j, w j * f j = 0) :
    denseCodesignAction lambda w f i = -lambda * f i := by
  rw [denseCodesignAction_mass_one lambda w f i hmass, hcenter]
  ring

/-- New permitted-edge columns multiplied by zero leave every finite affine
edge action unchanged.  This is the algebraic core of certified edge addition
by zero extension. -/
theorem edgeAddition_zeroExtension
    (oldColumn : R → E → ℝ) (newColumn : R → K → ℝ)
    (gamma : E → ℝ) (r : R) :
    (∑ e, oldColumn r e * gamma e) +
        (∑ k, newColumn r k * 0) =
      ∑ e, oldColumn r e * gamma e := by
  simp

/-- Comparing an exact proximal subproblem with its incumbent gives monotone
objective descent once the squared-distance penalty is nonnegative. -/
theorem proximalComparison_descent
    (before after step alpha : ℝ)
    (halpha : 0 < alpha)
    (hcompare : after + step ^ 2 / (2 * alpha) ≤ before) :
    after ≤ before := by
  have hpenalty : 0 ≤ step ^ 2 / (2 * alpha) := by
    positivity
  linarith

/-- The same comparison controls the squared increment by the objective drop. -/
theorem proximalComparison_square_bound
    (before after step alpha : ℝ)
    (halpha : 0 < alpha)
    (hcompare : after + step ^ 2 / (2 * alpha) ≤ before) :
    step ^ 2 ≤ 2 * alpha * (before - after) := by
  have hden : 0 < 2 * alpha := by positivity
  have hquot : step ^ 2 / (2 * alpha) ≤ before - after := by
    linarith
  have hmul := (div_le_iff₀ hden).mp hquot
  nlinarith

/-- The P1B coefficient times the accepted P1E rate cap is exactly six. -/
theorem paperI_codesign_frontier_constant :
    (3 / (32 * Real.pi ^ 2)) * (64 * Real.pi ^ 2) = (6 : ℝ) := by
  have hpi : Real.pi ≠ 0 := ne_of_gt Real.pi_pos
  field_simp [hpi]
  ring

end AFPBarrier
