import AFPBarrier.AccelerationFixedPoint
import AFPBarrier.AntipodalFeasibility
import AFPBarrier.CompleteGraph
import AFPBarrier.ConvexGeneratorDesign
import AFPBarrier.DiffusionProperty
import AFPBarrier.DualCertificate
import AFPBarrier.EnergyLossAngularDiffusion
import AFPBarrier.EqualAngleAsymptotics
import AFPBarrier.EqualAngleConnectivity
import AFPBarrier.EqualAngleDotProducts
import AFPBarrier.EqualAngleEdges
import AFPBarrier.EqualAngleGeometry
import AFPBarrier.EqualAngleGrid
import AFPBarrier.EqualAngleProduct
import AFPBarrier.EqualAngleQuadrature
import AFPBarrier.EqualAngleRateMaximum
import AFPBarrier.ExactLocalRows
import AFPBarrier.ExplicitEulerTransport
import AFPBarrier.ForwardAdjoint
import AFPBarrier.ForwardPeakedHeatKernel
import AFPBarrier.GlobalLossRigidity
import AFPBarrier.GlobalSharedEdgeDuality
import AFPBarrier.GroupAveraging
import AFPBarrier.HarmonicDefectTransport
import AFPBarrier.ImplementationConvention
import AFPBarrier.JumpGenerator
import AFPBarrier.LocalSphericalFeasibility
import AFPBarrier.LossVariance
import AFPBarrier.LossVarianceSharpness
import AFPBarrier.MultigroupTransfer
import AFPBarrier.NoGo
import AFPBarrier.NormalizationAudit
import AFPBarrier.OneShellQuadraticRigidity
import AFPBarrier.QEqualityCovariance
import AFPBarrier.QuadraticCovariance
import AFPBarrier.QuadraticEqualityGeometry
import AFPBarrier.QuadraticFidelityConstruction
import AFPBarrier.QuadraticFidelityFoundation
import AFPBarrier.QuadraticFidelityLowerBound
import AFPBarrier.QuadraticFidelityStability
import AFPBarrier.QuadraticSampling
import AFPBarrier.QuadraticSphereResidual
import AFPBarrier.Quantitative
import AFPBarrier.QuantitativeExactLocal
import AFPBarrier.QuantitativeGlobalNearRigidity
import AFPBarrier.QuantitativeSphericalFeasibility
import AFPBarrier.QuasiUniformLossBounds
import AFPBarrier.ReversibleConductance
import AFPBarrier.ScalingCompatibility
import AFPBarrier.SharedEdgeEquilibrium
import AFPBarrier.SharpProductBarriers
import AFPBarrier.SpatialUpwindTransport
import AFPBarrier.SpectralProductAlgebra
import AFPBarrier.SpectralSamplingObstruction
import AFPBarrier.SphereSpecialization
import AFPBarrier.SphericalFeasibilityAlgebra
import AFPBarrier.SphericalNetScaling
import AFPBarrier.SphericalQEqualityRigidity

/-! AFP R6 exhaustive generated signature and axiom audit.

Generated by `release/tools/generate_lean_release_audit.py`.
Do not hand-edit. Every public project theorem/lemma receives both
`#check` and `#print axioms`; analytic manuscript arguments remain
outside this finite formal surface.
-/

/-! 512 declarations. -/

-- AFPBarrier/AccelerationFixedPoint.lean:19
#check AFPBarrier.residualCorrection_fixedPoint
#print axioms AFPBarrier.residualCorrection_fixedPoint
-- AFPBarrier/AccelerationFixedPoint.lean:26
#check AFPBarrier.residualCorrection_error
#print axioms AFPBarrier.residualCorrection_error
-- AFPBarrier/AccelerationFixedPoint.lean:37
#check AFPBarrier.residualCorrection_preservesConstraint
#print axioms AFPBarrier.residualCorrection_preservesConstraint
-- AFPBarrier/AccelerationFixedPoint.lean:46
#check AFPBarrier.scalarShell_errorFactor
#print axioms AFPBarrier.scalarShell_errorFactor
-- AFPBarrier/AntipodalFeasibility.lean:22
#check AFPBarrier.antipodalOnlyFeasible_iff_simplex
#print axioms AFPBarrier.antipodalOnlyFeasible_iff_simplex
-- AFPBarrier/AntipodalFeasibility.lean:34
#check AFPBarrier.antipodalOnlyFeasible_of_positive_simplex
#print axioms AFPBarrier.antipodalOnlyFeasible_of_positive_simplex
-- AFPBarrier/AntipodalFeasibility.lean:45
#check AFPBarrier.uniformAntipodalRate_strictly_feasible
#print axioms AFPBarrier.uniformAntipodalRate_strictly_feasible
-- AFPBarrier/AntipodalFeasibility.lean:71
#check AFPBarrier.rowRateFromTangentWeight_nonneg
#print axioms AFPBarrier.rowRateFromTangentWeight_nonneg
-- AFPBarrier/AntipodalFeasibility.lean:79
#check AFPBarrier.rowRateFromTangentWeight_pos
#print axioms AFPBarrier.rowRateFromTangentWeight_pos
-- AFPBarrier/AntipodalFeasibility.lean:87
#check AFPBarrier.rowRateFromTangentWeight_balance
#print axioms AFPBarrier.rowRateFromTangentWeight_balance
-- AFPBarrier/AntipodalFeasibility.lean:108
#check AFPBarrier.rowRateFromTangentWeight_normal
#print axioms AFPBarrier.rowRateFromTangentWeight_normal
-- AFPBarrier/AntipodalFeasibility.lean:124
#check AFPBarrier.rowRateFromTangentDependenceWeight
#print axioms AFPBarrier.rowRateFromTangentDependenceWeight
-- AFPBarrier/AntipodalFeasibility.lean:133
#check AFPBarrier.mixedRow_from_tangentBudget
#print axioms AFPBarrier.mixedRow_from_tangentBudget
-- AFPBarrier/AntipodalFeasibility.lean:157
#check AFPBarrier.mixedRow_to_tangentBudget
#print axioms AFPBarrier.mixedRow_to_tangentBudget
-- AFPBarrier/AntipodalFeasibility.lean:183
#check AFPBarrier.mixedRow_tangentNormalBudget_bounds
#print axioms AFPBarrier.mixedRow_tangentNormalBudget_bounds
-- AFPBarrier/AntipodalFeasibility.lean:244
#check AFPBarrier.mixedRowFeasible_iff_exists_tangentParameter
#print axioms AFPBarrier.mixedRowFeasible_iff_exists_tangentParameter
-- AFPBarrier/AntipodalFeasibility.lean:276
#check AFPBarrier.mixedNormalBudgetFeasible_iff_remaining
#print axioms AFPBarrier.mixedNormalBudgetFeasible_iff_remaining
-- AFPBarrier/AntipodalFeasibility.lean:287
#check AFPBarrier.scaledAntipodalAllocation_sum
#print axioms AFPBarrier.scaledAntipodalAllocation_sum
-- AFPBarrier/AntipodalFeasibility.lean:294
#check AFPBarrier.scaledAntipodalAllocation_nonneg
#print axioms AFPBarrier.scaledAntipodalAllocation_nonneg
-- AFPBarrier/AntipodalFeasibility.lean:303
#check AFPBarrier.scaledAntipodalAllocation_pos
#print axioms AFPBarrier.scaledAntipodalAllocation_pos
-- AFPBarrier/AntipodalFeasibility.lean:312
#check AFPBarrier.mixedNormalBudgetFeasible_scaledAntipodalAllocation
#print axioms AFPBarrier.mixedNormalBudgetFeasible_scaledAntipodalAllocation
-- AFPBarrier/AntipodalFeasibility.lean:327
#check AFPBarrier.mixedNormalBudgetFeasible_zero_tangent
#print axioms AFPBarrier.mixedNormalBudgetFeasible_zero_tangent
-- AFPBarrier/AntipodalFeasibility.lean:334
#check AFPBarrier.mixedNormalBudgetFeasible_zero_tangent_uniform
#print axioms AFPBarrier.mixedNormalBudgetFeasible_zero_tangent_uniform
-- AFPBarrier/CompleteGraph.lean:33
#check AFPBarrier.completeConductance_symm
#print axioms AFPBarrier.completeConductance_symm
-- AFPBarrier/CompleteGraph.lean:41
#check AFPBarrier.conductanceRate_completeConductance_eq_completeRate
#print axioms AFPBarrier.conductanceRate_completeConductance_eq_completeRate
-- AFPBarrier/CompleteGraph.lean:52
#check AFPBarrier.completeRate_eigen_of_weightedMean_zero
#print axioms AFPBarrier.completeRate_eigen_of_weightedMean_zero
-- AFPBarrier/CompleteGraph.lean:93
#check AFPBarrier.completeRate_pos
#print axioms AFPBarrier.completeRate_pos
-- AFPBarrier/CompleteGraph.lean:104
#check AFPBarrier.completeConductance_pos
#print axioms AFPBarrier.completeConductance_pos
-- AFPBarrier/CompleteGraph.lean:116
#check AFPBarrier.completeRate_preserves_centered_coordinates
#print axioms AFPBarrier.completeRate_preserves_centered_coordinates
-- AFPBarrier/CompleteGraph.lean:132
#check AFPBarrier.reversible_coordinate_exactness_implies_centered
#print axioms AFPBarrier.reversible_coordinate_exactness_implies_centered
-- AFPBarrier/ConvexGeneratorDesign.lean:31
#check AFPBarrier.convexDesign_constant_exact
#print axioms AFPBarrier.convexDesign_constant_exact
-- AFPBarrier/ConvexGeneratorDesign.lean:38
#check AFPBarrier.convexDesign_rate_nonneg
#print axioms AFPBarrier.convexDesign_rate_nonneg
-- AFPBarrier/ConvexGeneratorDesign.lean:48
#check AFPBarrier.convexDesign_detailedBalance
#print axioms AFPBarrier.convexDesign_detailedBalance
-- AFPBarrier/ConvexGeneratorDesign.lean:64
#check AFPBarrier.conductanceMix_nonneg
#print axioms AFPBarrier.conductanceMix_nonneg
-- AFPBarrier/ConvexGeneratorDesign.lean:76
#check AFPBarrier.sharedEdgeApply_conductanceMix
#print axioms AFPBarrier.sharedEdgeApply_conductanceMix
-- AFPBarrier/ConvexGeneratorDesign.lean:92
#check AFPBarrier.sharedEdge_exact_conductanceMix
#print axioms AFPBarrier.sharedEdge_exact_conductanceMix
-- AFPBarrier/ConvexGeneratorDesign.lean:107
#check AFPBarrier.finiteMatrixApply_conductanceMix_le
#print axioms AFPBarrier.finiteMatrixApply_conductanceMix_le
-- AFPBarrier/ConvexGeneratorDesign.lean:145
#check AFPBarrier.affineShellResidual_conductanceMix
#print axioms AFPBarrier.affineShellResidual_conductanceMix
-- AFPBarrier/ConvexGeneratorDesign.lean:178
#check AFPBarrier.sum_incidentLossMass
#print axioms AFPBarrier.sum_incidentLossMass
-- AFPBarrier/ConvexGeneratorDesign.lean:200
#check AFPBarrier.lossWeightedTotal_fixed_of_radialExact
#print axioms AFPBarrier.lossWeightedTotal_fixed_of_radialExact
-- AFPBarrier/ConvexGeneratorDesign.lean:223
#check AFPBarrier.S2_lossWeightedTotal_one
#print axioms AFPBarrier.S2_lossWeightedTotal_one
-- AFPBarrier/ConvexGeneratorDesign.lean:236
#check AFPBarrier.totalConductance_fixed_of_constantLoss
#print axioms AFPBarrier.totalConductance_fixed_of_constantLoss
-- AFPBarrier/ConvexGeneratorDesign.lean:261
#check AFPBarrier.rateCapped_dualWork_nonneg
#print axioms AFPBarrier.rateCapped_dualWork_nonneg
-- AFPBarrier/ConvexGeneratorDesign.lean:313
#check AFPBarrier.rateCapped_negative_dualWork_certifies_infeasible
#print axioms AFPBarrier.rateCapped_negative_dualWork_certifies_infeasible
-- AFPBarrier/DiffusionProperty.lean:25
#check AFPBarrier.jumpGenerator_chain_rule_defect
#print axioms AFPBarrier.jumpGenerator_chain_rule_defect
-- AFPBarrier/DiffusionProperty.lean:44
#check AFPBarrier.strict_tangent_chain_rule_forces_generator_zero
#print axioms AFPBarrier.strict_tangent_chain_rule_forces_generator_zero
-- AFPBarrier/DiffusionProperty.lean:92
#check AFPBarrier.square_chain_rule_forces_generator_zero
#print axioms AFPBarrier.square_chain_rule_forces_generator_zero
-- AFPBarrier/DualCertificate.lean:34
#check AFPBarrier.finiteMatrix_bilinear_identity
#print axioms AFPBarrier.finiteMatrix_bilinear_identity
-- AFPBarrier/DualCertificate.lean:65
#check AFPBarrier.nonnegative_solution_forces_dualWork_nonneg
#print axioms AFPBarrier.nonnegative_solution_forces_dualWork_nonneg
-- AFPBarrier/DualCertificate.lean:86
#check AFPBarrier.negative_dualWork_certifies_infeasible
#print axioms AFPBarrier.negative_dualWork_certifies_infeasible
-- AFPBarrier/DualCertificate.lean:103
#check AFPBarrier.positiveLP_weak_duality
#print axioms AFPBarrier.positiveLP_weak_duality
-- AFPBarrier/EnergyLossAngularDiffusion.lean:39
#check AFPBarrier.inverseSquareAngularDepth_eq_reciprocal_difference
#print axioms AFPBarrier.inverseSquareAngularDepth_eq_reciprocal_difference
-- AFPBarrier/EnergyLossAngularDiffusion.lean:61
#check AFPBarrier.inverseSquareAngularDepth_nonneg
#print axioms AFPBarrier.inverseSquareAngularDepth_nonneg
-- AFPBarrier/EnergyLossAngularDiffusion.lean:73
#check AFPBarrier.twoLayer_energy_order_invariant
#print axioms AFPBarrier.twoLayer_energy_order_invariant
-- AFPBarrier/EnergyLossAngularDiffusion.lean:98
#check AFPBarrier.twoLayerAngularDepth_order_difference
#print axioms AFPBarrier.twoLayerAngularDepth_order_difference
-- AFPBarrier/EnergyLossAngularDiffusion.lean:120
#check AFPBarrier.twoLayerAngularDepth12_le_21
#print axioms AFPBarrier.twoLayerAngularDepth12_le_21
-- AFPBarrier/EnergyLossAngularDiffusion.lean:142
#check AFPBarrier.layeredAngularAmplitude_mul
#print axioms AFPBarrier.layeredAngularAmplitude_mul
-- AFPBarrier/EqualAngleAsymptotics.lean:39
#check AFPBarrier.squareRingDefect_between_sin_bounds
#print axioms AFPBarrier.squareRingDefect_between_sin_bounds
-- AFPBarrier/EqualAngleAsymptotics.lean:54
#check AFPBarrier.squareRingDefect_trig_bounds
#print axioms AFPBarrier.squareRingDefect_trig_bounds
-- AFPBarrier/EqualAngleAsymptotics.lean:77
#check AFPBarrier.equalAngleGrid_jordanScale
#print axioms AFPBarrier.equalAngleGrid_jordanScale
-- AFPBarrier/EqualAngleAsymptotics.lean:85
#check AFPBarrier.squareRingDefect_grid_bounds
#print axioms AFPBarrier.squareRingDefect_grid_bounds
-- AFPBarrier/EqualAngleAsymptotics.lean:115
#check AFPBarrier.squarePolarRate_lower_step
#print axioms AFPBarrier.squarePolarRate_lower_step
-- AFPBarrier/EqualAngleAsymptotics.lean:141
#check AFPBarrier.squarePolarRate_upper_jordan
#print axioms AFPBarrier.squarePolarRate_upper_jordan
-- AFPBarrier/EqualAngleAsymptotics.lean:177
#check AFPBarrier.squarePolarRate_grid_bounds
#print axioms AFPBarrier.squarePolarRate_grid_bounds
-- AFPBarrier/EqualAngleConnectivity.lean:18
#check AFPBarrier.equalAngleGridTheta_add_one
#print axioms AFPBarrier.equalAngleGridTheta_add_one
-- AFPBarrier/EqualAngleConnectivity.lean:27
#check AFPBarrier.equalAngleGrid_meridional_shared
#print axioms AFPBarrier.equalAngleGrid_meridional_shared
-- AFPBarrier/EqualAngleConnectivity.lean:40
#check AFPBarrier.equalAngleGridTheta_reflect
#print axioms AFPBarrier.equalAngleGridTheta_reflect
-- AFPBarrier/EqualAngleConnectivity.lean:50
#check AFPBarrier.equalAngleGrid_weight_reflect
#print axioms AFPBarrier.equalAngleGrid_weight_reflect
-- AFPBarrier/EqualAngleConnectivity.lean:65
#check AFPBarrier.equalAngleGrid_cos_reflect
#print axioms AFPBarrier.equalAngleGrid_cos_reflect
-- AFPBarrier/EqualAngleDotProducts.lean:26
#check AFPBarrier.sphericalCoordinateDot_meridional
#print axioms AFPBarrier.sphericalCoordinateDot_meridional
-- AFPBarrier/EqualAngleDotProducts.lean:39
#check AFPBarrier.sphericalCoordinateDot_azimuthal
#print axioms AFPBarrier.sphericalCoordinateDot_azimuthal
-- AFPBarrier/EqualAngleDotProducts.lean:54
#check AFPBarrier.meridionalDotLoss_eq_two_sin_sq
#print axioms AFPBarrier.meridionalDotLoss_eq_two_sin_sq
-- AFPBarrier/EqualAngleDotProducts.lean:66
#check AFPBarrier.azimuthalDotLoss_eq_sin_sq_mul
#print axioms AFPBarrier.azimuthalDotLoss_eq_sin_sq_mul
-- AFPBarrier/EqualAngleDotProducts.lean:77
#check AFPBarrier.equalAngle_actual_peakDefect_formula
#print axioms AFPBarrier.equalAngle_actual_peakDefect_formula
-- AFPBarrier/EqualAngleEdges.lean:19
#check AFPBarrier.equalAngleGrid_meridionalMinus_zero_north
#print axioms AFPBarrier.equalAngleGrid_meridionalMinus_zero_north
-- AFPBarrier/EqualAngleEdges.lean:29
#check AFPBarrier.equalAngleGrid_meridionalPlus_zero_south
#print axioms AFPBarrier.equalAngleGrid_meridionalPlus_zero_south
-- AFPBarrier/EqualAngleEdges.lean:45
#check AFPBarrier.equalAngleGrid_two_mul_order_mul_halfStep
#print axioms AFPBarrier.equalAngleGrid_two_mul_order_mul_halfStep
-- AFPBarrier/EqualAngleEdges.lean:52
#check AFPBarrier.equalAngleGrid_meridionalMinus_pos
#print axioms AFPBarrier.equalAngleGrid_meridionalMinus_pos
-- AFPBarrier/EqualAngleEdges.lean:91
#check AFPBarrier.equalAngleGrid_meridionalPlus_pos
#print axioms AFPBarrier.equalAngleGrid_meridionalPlus_pos
-- AFPBarrier/EqualAngleEdges.lean:132
#check AFPBarrier.equalAngleGrid_azimuthConductance_pos
#print axioms AFPBarrier.equalAngleGrid_azimuthConductance_pos
-- AFPBarrier/EqualAngleGeometry.lean:42
#check AFPBarrier.equalAngleTrigWeight_pos
#print axioms AFPBarrier.equalAngleTrigWeight_pos
-- AFPBarrier/EqualAngleGeometry.lean:54
#check AFPBarrier.equalAngleMeridionalMinus_pos
#print axioms AFPBarrier.equalAngleMeridionalMinus_pos
-- AFPBarrier/EqualAngleGeometry.lean:66
#check AFPBarrier.equalAngleMeridionalPlus_pos
#print axioms AFPBarrier.equalAngleMeridionalPlus_pos
-- AFPBarrier/EqualAngleGeometry.lean:79
#check AFPBarrier.equalAngleTrigAzimuthConductance_pos
#print axioms AFPBarrier.equalAngleTrigAzimuthConductance_pos
-- AFPBarrier/EqualAngleGeometry.lean:94
#check AFPBarrier.equalAngle_meridional_sum_trig
#print axioms AFPBarrier.equalAngle_meridional_sum_trig
-- AFPBarrier/EqualAngleGeometry.lean:107
#check AFPBarrier.equalAngle_axial_balance_trig
#print axioms AFPBarrier.equalAngle_axial_balance_trig
-- AFPBarrier/EqualAngleGeometry.lean:127
#check AFPBarrier.equalAngle_transverse_meridional_balance_trig
#print axioms AFPBarrier.equalAngle_transverse_meridional_balance_trig
-- AFPBarrier/EqualAngleGeometry.lean:148
#check AFPBarrier.equalAngle_azimuth_cos_balance_trig
#print axioms AFPBarrier.equalAngle_azimuth_cos_balance_trig
-- AFPBarrier/EqualAngleGeometry.lean:165
#check AFPBarrier.equalAngle_azimuth_sin_balance_trig
#print axioms AFPBarrier.equalAngle_azimuth_sin_balance_trig
-- AFPBarrier/EqualAngleGeometry.lean:183
#check AFPBarrier.equalAngle_productNodeAction_cos_eq
#print axioms AFPBarrier.equalAngle_productNodeAction_cos_eq
-- AFPBarrier/EqualAngleGeometry.lean:211
#check AFPBarrier.equalAngle_productNodeAction_sin_cos_eq
#print axioms AFPBarrier.equalAngle_productNodeAction_sin_cos_eq
-- AFPBarrier/EqualAngleGeometry.lean:283
#check AFPBarrier.equalAngle_productNodeAction_sin_sin_eq
#print axioms AFPBarrier.equalAngle_productNodeAction_sin_sin_eq
-- AFPBarrier/EqualAngleGrid.lean:34
#check AFPBarrier.equalAngleGridHalfStep_pos
#print axioms AFPBarrier.equalAngleGridHalfStep_pos
-- AFPBarrier/EqualAngleGrid.lean:41
#check AFPBarrier.equalAngleGridHalfStep_lt_pi_div_two
#print axioms AFPBarrier.equalAngleGridHalfStep_lt_pi_div_two
-- AFPBarrier/EqualAngleGrid.lean:50
#check AFPBarrier.equalAngleGridTheta_pos
#print axioms AFPBarrier.equalAngleGridTheta_pos
-- AFPBarrier/EqualAngleGrid.lean:57
#check AFPBarrier.equalAngleGridTheta_lt_pi
#print axioms AFPBarrier.equalAngleGridTheta_lt_pi
-- AFPBarrier/EqualAngleGrid.lean:67
#check AFPBarrier.equalAngleGridAzimuthStep_pos
#print axioms AFPBarrier.equalAngleGridAzimuthStep_pos
-- AFPBarrier/EqualAngleGrid.lean:74
#check AFPBarrier.equalAngleGridAzimuthStep_lt_two_pi
#print axioms AFPBarrier.equalAngleGridAzimuthStep_lt_two_pi
-- AFPBarrier/EqualAngleGrid.lean:84
#check AFPBarrier.one_sub_cos_pos_of_pos_of_lt_two_pi
#print axioms AFPBarrier.one_sub_cos_pos_of_pos_of_lt_two_pi
-- AFPBarrier/EqualAngleGrid.lean:99
#check AFPBarrier.equalAngleGrid_parameter_facts
#print axioms AFPBarrier.equalAngleGrid_parameter_facts
-- AFPBarrier/EqualAngleGrid.lean:133
#check AFPBarrier.equalAngleGrid_weight_pos
#print axioms AFPBarrier.equalAngleGrid_weight_pos
-- AFPBarrier/EqualAngleGrid.lean:154
#check AFPBarrier.equalAngleGrid_coordinate_exact
#print axioms AFPBarrier.equalAngleGrid_coordinate_exact
-- AFPBarrier/EqualAngleProduct.lean:36
#check AFPBarrier.productNodeAction_const
#print axioms AFPBarrier.productNodeAction_const
-- AFPBarrier/EqualAngleProduct.lean:43
#check AFPBarrier.productNodeAction_eq_of_balance
#print axioms AFPBarrier.productNodeAction_eq_of_balance
-- AFPBarrier/EqualAngleProduct.lean:57
#check AFPBarrier.productNodeAction_axial
#print axioms AFPBarrier.productNodeAction_axial
-- AFPBarrier/EqualAngleProduct.lean:92
#check AFPBarrier.equalAngleWeight_pos
#print axioms AFPBarrier.equalAngleWeight_pos
-- AFPBarrier/EqualAngleProduct.lean:100
#check AFPBarrier.equalAngleMeridionalTotal_pos
#print axioms AFPBarrier.equalAngleMeridionalTotal_pos
-- AFPBarrier/EqualAngleProduct.lean:108
#check AFPBarrier.equalAngleAzimuthConductance_pos
#print axioms AFPBarrier.equalAngleAzimuthConductance_pos
-- AFPBarrier/EqualAngleProduct.lean:117
#check AFPBarrier.equalAngle_meridional_rate
#print axioms AFPBarrier.equalAngle_meridional_rate
-- AFPBarrier/EqualAngleProduct.lean:128
#check AFPBarrier.equalAngle_azimuth_rate
#print axioms AFPBarrier.equalAngle_azimuth_rate
-- AFPBarrier/EqualAngleProduct.lean:144
#check AFPBarrier.equalAngle_peakDefect_formula
#print axioms AFPBarrier.equalAngle_peakDefect_formula
-- AFPBarrier/EqualAngleProduct.lean:161
#check AFPBarrier.equalAngle_rate_formula
#print axioms AFPBarrier.equalAngle_rate_formula
-- AFPBarrier/EqualAngleProduct.lean:178
#check AFPBarrier.squarePolar_rate_formula
#print axioms AFPBarrier.squarePolar_rate_formula
-- AFPBarrier/EqualAngleProduct.lean:195
#check AFPBarrier.squarePolar_peakDefect_formula
#print axioms AFPBarrier.squarePolar_peakDefect_formula
-- AFPBarrier/EqualAngleProduct.lean:214
#check AFPBarrier.equalAngle_defect_pos
#print axioms AFPBarrier.equalAngle_defect_pos
-- AFPBarrier/EqualAngleQuadrature.lean:17
#check AFPBarrier.sum_range_sub_succ_real
#print axioms AFPBarrier.sum_range_sub_succ_real
-- AFPBarrier/EqualAngleQuadrature.lean:28
#check AFPBarrier.equalAngleTrigWeight_eq_cos_difference
#print axioms AFPBarrier.equalAngleTrigWeight_eq_cos_difference
-- AFPBarrier/EqualAngleQuadrature.lean:37
#check AFPBarrier.equalAngleGrid_weight_telescope
#print axioms AFPBarrier.equalAngleGrid_weight_telescope
-- AFPBarrier/EqualAngleQuadrature.lean:54
#check AFPBarrier.sum_equalAngleGrid_ringWeights
#print axioms AFPBarrier.sum_equalAngleGrid_ringWeights
-- AFPBarrier/EqualAngleQuadrature.lean:87
#check AFPBarrier.sum_equalAngleGrid_allWeights
#print axioms AFPBarrier.sum_equalAngleGrid_allWeights
-- AFPBarrier/EqualAngleRateMaximum.lean:20
#check AFPBarrier.sin_halfStep_le_of_mem_symmetric_interval
#print axioms AFPBarrier.sin_halfStep_le_of_mem_symmetric_interval
-- AFPBarrier/EqualAngleRateMaximum.lean:35
#check AFPBarrier.equalAngleGridTheta_mem_symmetric_interval
#print axioms AFPBarrier.equalAngleGridTheta_mem_symmetric_interval
-- AFPBarrier/EqualAngleRateMaximum.lean:56
#check AFPBarrier.equalAngleGrid_sin_halfStep_le_sin_theta
#print axioms AFPBarrier.equalAngleGrid_sin_halfStep_le_sin_theta
-- AFPBarrier/EqualAngleRateMaximum.lean:71
#check AFPBarrier.squareRingRate_le_polar_of_sin_sq
#print axioms AFPBarrier.squareRingRate_le_polar_of_sin_sq
-- AFPBarrier/EqualAngleRateMaximum.lean:96
#check AFPBarrier.equalAngleGrid_squareRingRate_le_polar
#print axioms AFPBarrier.equalAngleGrid_squareRingRate_le_polar
-- AFPBarrier/ExactLocalRows.lean:35
#check AFPBarrier.normalizedAngularScale_pos
#print axioms AFPBarrier.normalizedAngularScale_pos
-- AFPBarrier/ExactLocalRows.lean:59
#check AFPBarrier.exactLocalRowRate_nonneg
#print axioms AFPBarrier.exactLocalRowRate_nonneg
-- AFPBarrier/ExactLocalRows.lean:71
#check AFPBarrier.exactLocalRowRate_pos
#print axioms AFPBarrier.exactLocalRowRate_pos
-- AFPBarrier/ExactLocalRows.lean:87
#check AFPBarrier.exactLocalRowRate_tangent_balance
#print axioms AFPBarrier.exactLocalRowRate_tangent_balance
-- AFPBarrier/ExactLocalRows.lean:104
#check AFPBarrier.exactLocalRowRate_normal_balance
#print axioms AFPBarrier.exactLocalRowRate_normal_balance
-- AFPBarrier/ExactLocalRows.lean:123
#check AFPBarrier.exactLocalRowRate_sum
#print axioms AFPBarrier.exactLocalRowRate_sum
-- AFPBarrier/ExactLocalRows.lean:136
#check AFPBarrier.tangentMass_pos_of_normal_balance
#print axioms AFPBarrier.tangentMass_pos_of_normal_balance
-- AFPBarrier/ExactLocalRows.lean:162
#check AFPBarrier.normalizedTangentWeight_nonneg
#print axioms AFPBarrier.normalizedTangentWeight_nonneg
-- AFPBarrier/ExactLocalRows.lean:172
#check AFPBarrier.normalizedTangentWeight_sum
#print axioms AFPBarrier.normalizedTangentWeight_sum
-- AFPBarrier/ExactLocalRows.lean:192
#check AFPBarrier.normalizedTangentWeight_balance
#print axioms AFPBarrier.normalizedTangentWeight_balance
-- AFPBarrier/ExactLocalRows.lean:212
#check AFPBarrier.normalizedAngularScale_normalizedTangentWeight
#print axioms AFPBarrier.normalizedAngularScale_normalizedTangentWeight
-- AFPBarrier/ExactLocalRows.lean:232
#check AFPBarrier.exactLocalRowRate_recover
#print axioms AFPBarrier.exactLocalRowRate_recover
-- AFPBarrier/ExplicitEulerTransport.lean:36
#check AFPBarrier.explicitEulerStep_eq_self_weight_add_neighbors
#print axioms AFPBarrier.explicitEulerStep_eq_self_weight_add_neighbors
-- AFPBarrier/ExplicitEulerTransport.lean:63
#check AFPBarrier.explicitEulerStep_eigenmode
#print axioms AFPBarrier.explicitEulerStep_eigenmode
-- AFPBarrier/ExplicitEulerTransport.lean:72
#check AFPBarrier.explicitEulerStep_nonneg
#print axioms AFPBarrier.explicitEulerStep_nonneg
-- AFPBarrier/ExplicitEulerTransport.lean:91
#check AFPBarrier.unitAt_self
#print axioms AFPBarrier.unitAt_self
-- AFPBarrier/ExplicitEulerTransport.lean:94
#check AFPBarrier.unitAt_of_ne
#print axioms AFPBarrier.unitAt_of_ne
-- AFPBarrier/ExplicitEulerTransport.lean:98
#check AFPBarrier.explicitEulerStep_unitAt
#print axioms AFPBarrier.explicitEulerStep_unitAt
-- AFPBarrier/ExplicitEulerTransport.lean:112
#check AFPBarrier.explicitEulerStep_unitAt_neg_of_cfl_violation
#print axioms AFPBarrier.explicitEulerStep_unitAt_neg_of_cfl_violation
-- AFPBarrier/ExplicitEulerTransport.lean:120
#check AFPBarrier.weighted_sum_explicitEuler_conductanceRate
#print axioms AFPBarrier.weighted_sum_explicitEuler_conductanceRate
-- AFPBarrier/ForwardAdjoint.lean:26
#check AFPBarrier.weightedAdjointRate_nonneg
#print axioms AFPBarrier.weightedAdjointRate_nonneg
-- AFPBarrier/ForwardAdjoint.lean:40
#check AFPBarrier.jumpGenerator_weightedAdjointRate_eq
#print axioms AFPBarrier.jumpGenerator_weightedAdjointRate_eq
-- AFPBarrier/ForwardAdjoint.lean:83
#check AFPBarrier.jumpGenerator_weightedAdjointRate_eigen
#print axioms AFPBarrier.jumpGenerator_weightedAdjointRate_eigen
-- AFPBarrier/ForwardAdjoint.lean:106
#check AFPBarrier.no_exact_forward_linear_and_square_at_peak
#print axioms AFPBarrier.no_exact_forward_linear_and_square_at_peak
-- AFPBarrier/ForwardPeakedHeatKernel.lean:46
#check AFPBarrier.heatKernelScatterMoment_le_one
#print axioms AFPBarrier.heatKernelScatterMoment_le_one
-- AFPBarrier/ForwardPeakedHeatKernel.lean:56
#check AFPBarrier.heatKernelScatterMoment_pos
#print axioms AFPBarrier.heatKernelScatterMoment_pos
-- AFPBarrier/ForwardPeakedHeatKernel.lean:62
#check AFPBarrier.one_sub_tau_mul_le_heatKernelScatterMoment
#print axioms AFPBarrier.one_sub_tau_mul_le_heatKernelScatterMoment
-- AFPBarrier/ForwardPeakedHeatKernel.lean:70
#check AFPBarrier.heatKernelBoltzmannDecay_nonneg
#print axioms AFPBarrier.heatKernelBoltzmannDecay_nonneg
-- AFPBarrier/ForwardPeakedHeatKernel.lean:80
#check AFPBarrier.heatKernelBoltzmannDecay_le_fp
#print axioms AFPBarrier.heatKernelBoltzmannDecay_le_fp
-- AFPBarrier/ForwardPeakedHeatKernel.lean:90
#check AFPBarrier.fp_amplitude_le_heatKernelBoltzmann_amplitude
#print axioms AFPBarrier.fp_amplitude_le_heatKernelBoltzmann_amplitude
-- AFPBarrier/GlobalLossRigidity.lean:22
#check AFPBarrier.rate_eq_of_symmetric_active_loss
#print axioms AFPBarrier.rate_eq_of_symmetric_active_loss
-- AFPBarrier/GlobalLossRigidity.lean:50
#check AFPBarrier.rate_eq_of_active_reflTransGen
#print axioms AFPBarrier.rate_eq_of_active_reflTransGen
-- AFPBarrier/GlobalLossRigidity.lean:72
#check AFPBarrier.connected_active_loss_rigidity
#print axioms AFPBarrier.connected_active_loss_rigidity
-- AFPBarrier/GlobalSharedEdgeDuality.lean:31
#check AFPBarrier.sharedEdgeDualWork_swap
#print axioms AFPBarrier.sharedEdgeDualWork_swap
-- AFPBarrier/GlobalSharedEdgeDuality.lean:45
#check AFPBarrier.sharedEdgeDualWork_constant
#print axioms AFPBarrier.sharedEdgeDualWork_constant
-- AFPBarrier/GlobalSharedEdgeDuality.lean:56
#check AFPBarrier.sharedEdgeDualWork_radial
#print axioms AFPBarrier.sharedEdgeDualWork_radial
-- AFPBarrier/GlobalSharedEdgeDuality.lean:77
#check AFPBarrier.sharedEdgeDualWork_radial_nonneg
#print axioms AFPBarrier.sharedEdgeDualWork_radial_nonneg
-- AFPBarrier/GlobalSharedEdgeDuality.lean:95
#check AFPBarrier.positiveLPDualSlack_nonneg
#print axioms AFPBarrier.positiveLPDualSlack_nonneg
-- AFPBarrier/GlobalSharedEdgeDuality.lean:103
#check AFPBarrier.positiveLP_objectiveGap_eq_slackPairing
#print axioms AFPBarrier.positiveLP_objectiveGap_eq_slackPairing
-- AFPBarrier/GlobalSharedEdgeDuality.lean:128
#check AFPBarrier.positiveLP_complementaritySum_eq_zero
#print axioms AFPBarrier.positiveLP_complementaritySum_eq_zero
-- AFPBarrier/GlobalSharedEdgeDuality.lean:141
#check AFPBarrier.positiveLP_complementarySlackness
#print axioms AFPBarrier.positiveLP_complementarySlackness
-- AFPBarrier/GlobalSharedEdgeDuality.lean:161
#check AFPBarrier.positiveLP_active_forces_dualSaturation
#print axioms AFPBarrier.positiveLP_active_forces_dualSaturation
-- AFPBarrier/GlobalSharedEdgeDuality.lean:178
#check AFPBarrier.positiveLP_strictDualSlack_forces_inactive
#print axioms AFPBarrier.positiveLP_strictDualSlack_forces_inactive
-- AFPBarrier/GroupAveraging.lean:26
#check AFPBarrier.finiteAverage_const
#print axioms AFPBarrier.finiteAverage_const
-- AFPBarrier/GroupAveraging.lean:33
#check AFPBarrier.finiteAverage_mul
#print axioms AFPBarrier.finiteAverage_mul
-- AFPBarrier/GroupAveraging.lean:39
#check AFPBarrier.sum_finiteAverage
#print axioms AFPBarrier.sum_finiteAverage
-- AFPBarrier/GroupAveraging.lean:46
#check AFPBarrier.finiteAverage_nonneg
#print axioms AFPBarrier.finiteAverage_nonneg
-- AFPBarrier/GroupAveraging.lean:63
#check AFPBarrier.coordinateBalance_averagedConductance
#print axioms AFPBarrier.coordinateBalance_averagedConductance
-- AFPBarrier/GroupAveraging.lean:83
#check AFPBarrier.averagedConductance_nonneg
#print axioms AFPBarrier.averagedConductance_nonneg
-- AFPBarrier/GroupAveraging.lean:89
#check AFPBarrier.averagedConductance_symm
#print axioms AFPBarrier.averagedConductance_symm
-- AFPBarrier/GroupAveraging.lean:101
#check AFPBarrier.averagedConductance_balance
#print axioms AFPBarrier.averagedConductance_balance
-- AFPBarrier/GroupAveraging.lean:134
#check AFPBarrier.groupOrbitAverage_invariant
#print axioms AFPBarrier.groupOrbitAverage_invariant
-- AFPBarrier/GroupAveraging.lean:148
#check AFPBarrier.groupOrbitAverage_nonneg
#print axioms AFPBarrier.groupOrbitAverage_nonneg
-- AFPBarrier/GroupAveraging.lean:167
#check AFPBarrier.groupOrbitAverage_orientation_of_sameOrbit
#print axioms AFPBarrier.groupOrbitAverage_orientation_of_sameOrbit
-- AFPBarrier/GroupAveraging.lean:198
#check AFPBarrier.groupOrbitAverage_eq_zero_of_not_relation
#print axioms AFPBarrier.groupOrbitAverage_eq_zero_of_not_relation
-- AFPBarrier/GroupAveraging.lean:221
#check AFPBarrier.groupOrbitAverage_balance
#print axioms AFPBarrier.groupOrbitAverage_balance
-- AFPBarrier/GroupAveraging.lean:234
#check AFPBarrier.groupOrbitAverage_reconciliation
#print axioms AFPBarrier.groupOrbitAverage_reconciliation
-- AFPBarrier/GroupAveraging.lean:257
#check AFPBarrier.groupOrbitAverage_reconciliation_of_edgeRepresentative
#print axioms AFPBarrier.groupOrbitAverage_reconciliation_of_edgeRepresentative
-- AFPBarrier/HarmonicDefectTransport.lean:42
#check AFPBarrier.finiteDuhamel_norm_le
#print axioms AFPBarrier.finiteDuhamel_norm_le
-- AFPBarrier/HarmonicDefectTransport.lean:55
#check AFPBarrier.transientKernel_nonneg
#print axioms AFPBarrier.transientKernel_nonneg
-- AFPBarrier/HarmonicDefectTransport.lean:70
#check AFPBarrier.resolvent_residual_identity
#print axioms AFPBarrier.resolvent_residual_identity
-- AFPBarrier/HarmonicDefectTransport.lean:101
#check AFPBarrier.resolvent_residual_norm_le
#print axioms AFPBarrier.resolvent_residual_norm_le
-- AFPBarrier/HarmonicDefectTransport.lean:127
#check AFPBarrier.sixError_telescope
#print axioms AFPBarrier.sixError_telescope
-- AFPBarrier/HarmonicDefectTransport.lean:139
#check AFPBarrier.sixError_norm_le
#print axioms AFPBarrier.sixError_norm_le
-- AFPBarrier/HarmonicDefectTransport.lean:206
#check AFPBarrier.finitePair_transpose_apply
#print axioms AFPBarrier.finitePair_transpose_apply
-- AFPBarrier/HarmonicDefectTransport.lean:232
#check AFPBarrier.adjointWeightedResidual_exact
#print axioms AFPBarrier.adjointWeightedResidual_exact
-- AFPBarrier/HarmonicDefectTransport.lean:242
#check AFPBarrier.adjointWeightedResidual_approx
#print axioms AFPBarrier.adjointWeightedResidual_approx
-- AFPBarrier/HarmonicDefectTransport.lean:261
#check AFPBarrier.energyResidual_young
#print axioms AFPBarrier.energyResidual_young
-- AFPBarrier/HarmonicDefectTransport.lean:274
#check AFPBarrier.coerciveResidual_bound
#print axioms AFPBarrier.coerciveResidual_bound
-- AFPBarrier/HarmonicDefectTransport.lean:285
#check AFPBarrier.preconditionedIteration_geometric
#print axioms AFPBarrier.preconditionedIteration_geometric
-- AFPBarrier/HarmonicDefectTransport.lean:304
#check AFPBarrier.preconditionedGeometricSeries_le
#print axioms AFPBarrier.preconditionedGeometricSeries_le
-- AFPBarrier/ImplementationConvention.lean:34
#check AFPBarrier.matrixAction_conductanceMatrix_eq_jumpGenerator
#print axioms AFPBarrier.matrixAction_conductanceMatrix_eq_jumpGenerator
-- AFPBarrier/ImplementationConvention.lean:90
#check AFPBarrier.matrixAction_diagonalShift
#print axioms AFPBarrier.matrixAction_diagonalShift
-- AFPBarrier/ImplementationConvention.lean:110
#check AFPBarrier.shifted_source_minus_total_shift
#print axioms AFPBarrier.shifted_source_minus_total_shift
-- AFPBarrier/ImplementationConvention.lean:120
#check AFPBarrier.shifted_conductance_action_recovers_jumpGenerator
#print axioms AFPBarrier.shifted_conductance_action_recovers_jumpGenerator
-- AFPBarrier/JumpGenerator.lean:34
#check AFPBarrier.jumpGenerator_const
#print axioms AFPBarrier.jumpGenerator_const
-- AFPBarrier/JumpGenerator.lean:40
#check AFPBarrier.jumpGenerator_add_const
#print axioms AFPBarrier.jumpGenerator_add_const
-- AFPBarrier/JumpGenerator.lean:46
#check AFPBarrier.jumpGenerator_sub_const
#print axioms AFPBarrier.jumpGenerator_sub_const
-- AFPBarrier/JumpGenerator.lean:52
#check AFPBarrier.jumpGenerator_square_identity
#print axioms AFPBarrier.jumpGenerator_square_identity
-- AFPBarrier/JumpGenerator.lean:66
#check AFPBarrier.jumpRate_nonneg
#print axioms AFPBarrier.jumpRate_nonneg
-- AFPBarrier/JumpGenerator.lean:76
#check AFPBarrier.carreDuChamp_nonneg
#print axioms AFPBarrier.carreDuChamp_nonneg
-- AFPBarrier/JumpGenerator.lean:87
#check AFPBarrier.jumpGenerator_sq_le_rate_mul_carre
#print axioms AFPBarrier.jumpGenerator_sq_le_rate_mul_carre
-- AFPBarrier/JumpGenerator.lean:107
#check AFPBarrier.zero_carreDuChamp_forces_generator_zero
#print axioms AFPBarrier.zero_carreDuChamp_forces_generator_zero
-- AFPBarrier/LocalSphericalFeasibility.lean:43
#check AFPBarrier.scaledSphericalRowRate_nonneg
#print axioms AFPBarrier.scaledSphericalRowRate_nonneg
-- AFPBarrier/LocalSphericalFeasibility.lean:56
#check AFPBarrier.scaledSphericalRowRate_pos
#print axioms AFPBarrier.scaledSphericalRowRate_pos
-- AFPBarrier/LocalSphericalFeasibility.lean:67
#check AFPBarrier.scaledSphericalRowRate_tangent_balance
#print axioms AFPBarrier.scaledSphericalRowRate_tangent_balance
-- AFPBarrier/LocalSphericalFeasibility.lean:101
#check AFPBarrier.scaledSphericalRowRate_normal_balance
#print axioms AFPBarrier.scaledSphericalRowRate_normal_balance
-- AFPBarrier/LocalSphericalFeasibility.lean:133
#check AFPBarrier.tangentDependenceWeight_nonneg
#print axioms AFPBarrier.tangentDependenceWeight_nonneg
-- AFPBarrier/LocalSphericalFeasibility.lean:143
#check AFPBarrier.tangentDependenceWeight_balance
#print axioms AFPBarrier.tangentDependenceWeight_balance
-- AFPBarrier/LocalSphericalFeasibility.lean:155
#check AFPBarrier.tangentDependenceWeight_normal_scale
#print axioms AFPBarrier.tangentDependenceWeight_normal_scale
-- AFPBarrier/LossVariance.lean:14
#check AFPBarrier.lossVarianceAt_nonneg
#print axioms AFPBarrier.lossVarianceAt_nonneg
-- AFPBarrier/LossVariance.lean:24
#check AFPBarrier.carreDuChamp_centered_loss_identity
#print axioms AFPBarrier.carreDuChamp_centered_loss_identity
-- AFPBarrier/LossVariance.lean:40
#check AFPBarrier.peakDefect_centered_loss_identity
#print axioms AFPBarrier.peakDefect_centered_loss_identity
-- AFPBarrier/LossVariance.lean:55
#check AFPBarrier.rate_mul_peakDefect_sub_eigenvalue_sq_eq_rate_mul_lossVariance
#print axioms AFPBarrier.rate_mul_peakDefect_sub_eigenvalue_sq_eq_rate_mul_lossVariance
-- AFPBarrier/LossVariance.lean:78
#check AFPBarrier.squareRing_rate_mul_defect_sub_four
#print axioms AFPBarrier.squareRing_rate_mul_defect_sub_four
-- AFPBarrier/LossVariance.lean:86
#check AFPBarrier.four_le_squareRing_rate_mul_defect
#print axioms AFPBarrier.four_le_squareRing_rate_mul_defect
-- AFPBarrier/LossVarianceSharpness.lean:22
#check AFPBarrier.lossVarianceAt_eq_zero_iff_active_losses_eq
#print axioms AFPBarrier.lossVarianceAt_eq_zero_iff_active_losses_eq
-- AFPBarrier/LossVarianceSharpness.lean:57
#check AFPBarrier.rate_mul_peakDefect_eq_eigenvalue_sq_iff_active_losses_eq
#print axioms AFPBarrier.rate_mul_peakDefect_eq_eigenvalue_sq_iff_active_losses_eq
-- AFPBarrier/LossVarianceSharpness.lean:84
#check AFPBarrier.rate_mul_peakDefect_eq_eigenvalue_sq_iff_active_losses_eq_mean
#print axioms AFPBarrier.rate_mul_peakDefect_eq_eigenvalue_sq_iff_active_losses_eq_mean
-- AFPBarrier/LossVarianceSharpness.lean:101
#check AFPBarrier.active_weight_mul_loss_deviation_sq_le_variance
#print axioms AFPBarrier.active_weight_mul_loss_deviation_sq_le_variance
-- AFPBarrier/LossVarianceSharpness.lean:120
#check AFPBarrier.lossVarianceAt_le_gap_div_rate
#print axioms AFPBarrier.lossVarianceAt_le_gap_div_rate
-- AFPBarrier/LossVarianceSharpness.lean:140
#check AFPBarrier.minActiveRate_mul_loss_deviation_sq_le_gap_div_rate
#print axioms AFPBarrier.minActiveRate_mul_loss_deviation_sq_le_gap_div_rate
-- AFPBarrier/LossVarianceSharpness.lean:163
#check AFPBarrier.peakDefect_dual_tangent_lower_bound
#print axioms AFPBarrier.peakDefect_dual_tangent_lower_bound
-- AFPBarrier/LossVarianceSharpness.lean:177
#check AFPBarrier.peakDefect_ge_eigenvalue_sq_div_rate_via_dual
#print axioms AFPBarrier.peakDefect_ge_eigenvalue_sq_div_rate_via_dual
-- AFPBarrier/LossVarianceSharpness.lean:198
#check AFPBarrier.S2_rate_lower_of_peakDefect_upper
#print axioms AFPBarrier.S2_rate_lower_of_peakDefect_upper
-- AFPBarrier/MultigroupTransfer.lean:39
#check AFPBarrier.sum_multigroupTransfer_eq_zero
#print axioms AFPBarrier.sum_multigroupTransfer_eq_zero
-- AFPBarrier/MultigroupTransfer.lean:66
#check AFPBarrier.multigroupEulerStep_eq_positive_form
#print axioms AFPBarrier.multigroupEulerStep_eq_positive_form
-- AFPBarrier/MultigroupTransfer.lean:75
#check AFPBarrier.multigroupEulerStep_nonneg
#print axioms AFPBarrier.multigroupEulerStep_nonneg
-- AFPBarrier/MultigroupTransfer.lean:91
#check AFPBarrier.sum_multigroupEulerStep_eq_sum
#print axioms AFPBarrier.sum_multigroupEulerStep_eq_sum
-- AFPBarrier/MultigroupTransfer.lean:109
#check AFPBarrier.multigroupEulerStep_unitAt
#print axioms AFPBarrier.multigroupEulerStep_unitAt
-- AFPBarrier/MultigroupTransfer.lean:132
#check AFPBarrier.multigroupEulerStep_unitAt_neg_of_cfl_violation
#print axioms AFPBarrier.multigroupEulerStep_unitAt_neg_of_cfl_violation
-- AFPBarrier/MultigroupTransfer.lean:150
#check AFPBarrier.weighted_sum_multigroupTransfer_eq_neg_deposition
#print axioms AFPBarrier.weighted_sum_multigroupTransfer_eq_neg_deposition
-- AFPBarrier/NoGo.lean:17
#check AFPBarrier.no_exact_linear_and_square_at_peak
#print axioms AFPBarrier.no_exact_linear_and_square_at_peak
-- AFPBarrier/NoGo.lean:40
#check AFPBarrier.no_exact_shifted_quadratic_at_peak
#print axioms AFPBarrier.no_exact_shifted_quadratic_at_peak
-- AFPBarrier/NormalizationAudit.lean:24
#check AFPBarrier.conductance_eigen_iff_equilibrium
#print axioms AFPBarrier.conductance_eigen_iff_equilibrium
-- AFPBarrier/NormalizationAudit.lean:42
#check AFPBarrier.S2_coordinate_eigen_implies_minus_two_balance
#print axioms AFPBarrier.S2_coordinate_eigen_implies_minus_two_balance
-- AFPBarrier/NormalizationAudit.lean:53
#check AFPBarrier.minus_two_and_minus_four_balance_incompatible
#print axioms AFPBarrier.minus_two_and_minus_four_balance_incompatible
-- AFPBarrier/OneShellQuadraticRigidity.lean:47
#check AFPBarrier.oneShell_radial_rate
#print axioms AFPBarrier.oneShell_radial_rate
-- AFPBarrier/OneShellQuadraticRigidity.lean:125
#check AFPBarrier.oneShell_tangent_balance
#print axioms AFPBarrier.oneShell_tangent_balance
-- AFPBarrier/OneShellQuadraticRigidity.lean:169
#check AFPBarrier.oneShell_covariance_expansion
#print axioms AFPBarrier.oneShell_covariance_expansion
-- AFPBarrier/OneShellQuadraticRigidity.lean:213
#check AFPBarrier.oneShell_covariance_decomposition
#print axioms AFPBarrier.oneShell_covariance_decomposition
-- AFPBarrier/OneShellQuadraticRigidity.lean:252
#check AFPBarrier.oneShell_actual_covariance_decomposition
#print axioms AFPBarrier.oneShell_actual_covariance_decomposition
-- AFPBarrier/OneShellQuadraticRigidity.lean:276
#check AFPBarrier.oneShell_matrixFrobeniusPairing_add_right
#print axioms AFPBarrier.oneShell_matrixFrobeniusPairing_add_right
-- AFPBarrier/OneShellQuadraticRigidity.lean:286
#check AFPBarrier.oneShell_matrixFrobeniusPairing_smul_right
#print axioms AFPBarrier.oneShell_matrixFrobeniusPairing_smul_right
-- AFPBarrier/OneShellQuadraticRigidity.lean:302
#check AFPBarrier.oneShell_matrixFrobeniusPairing_one
#print axioms AFPBarrier.oneShell_matrixFrobeniusPairing_one
-- AFPBarrier/OneShellQuadraticRigidity.lean:313
#check AFPBarrier.oneShell_matrixFrobeniusPairing_vecMulVec
#print axioms AFPBarrier.oneShell_matrixFrobeniusPairing_vecMulVec
-- AFPBarrier/OneShellQuadraticRigidity.lean:328
#check AFPBarrier.oneShell_traceFree_residual_pairing
#print axioms AFPBarrier.oneShell_traceFree_residual_pairing
-- AFPBarrier/OneShellQuadraticRigidity.lean:361
#check AFPBarrier.oneShell_sphereResidual_row
#print axioms AFPBarrier.oneShell_sphereResidual_row
-- AFPBarrier/OneShellQuadraticRigidity.lean:395
#check AFPBarrier.oneShell_residual_factorization
#print axioms AFPBarrier.oneShell_residual_factorization
-- AFPBarrier/OneShellQuadraticRigidity.lean:404
#check AFPBarrier.oneShell_residualKernel_eq_samplingKernel
#print axioms AFPBarrier.oneShell_residualKernel_eq_samplingKernel
-- AFPBarrier/OneShellQuadraticRigidity.lean:426
#check AFPBarrier.oneShell_residualRank_eq_samplingRank
#print axioms AFPBarrier.oneShell_residualRank_eq_samplingRank
-- AFPBarrier/OneShellQuadraticRigidity.lean:440
#check AFPBarrier.oneShell_sampledExactRange_eq_bot
#print axioms AFPBarrier.oneShell_sampledExactRange_eq_bot
-- AFPBarrier/OneShellQuadraticRigidity.lean:460
#check AFPBarrier.oneShell_sphereResidual_factorization
#print axioms AFPBarrier.oneShell_sphereResidual_factorization
-- AFPBarrier/OneShellQuadraticRigidity.lean:480
#check AFPBarrier.oneShell_sphereScale_ne_zero
#print axioms AFPBarrier.oneShell_sphereScale_ne_zero
-- AFPBarrier/OneShellQuadraticRigidity.lean:491
#check AFPBarrier.oneShell_sphereResidualKernel_eq_samplingKernel
#print axioms AFPBarrier.oneShell_sphereResidualKernel_eq_samplingKernel
-- AFPBarrier/OneShellQuadraticRigidity.lean:513
#check AFPBarrier.oneShell_sphereResidualRank_eq_samplingRank
#print axioms AFPBarrier.oneShell_sphereResidualRank_eq_samplingRank
-- AFPBarrier/OneShellQuadraticRigidity.lean:536
#check AFPBarrier.oneShell_sphereSampledExactRange_eq_bot
#print axioms AFPBarrier.oneShell_sphereSampledExactRange_eq_bot
-- AFPBarrier/QEqualityCovariance.lean:24
#check AFPBarrier.covarianceTrace_eq_four_of_normLoss
#print axioms AFPBarrier.covarianceTrace_eq_four_of_normLoss
-- AFPBarrier/QEqualityCovariance.lean:44
#check AFPBarrier.radialCovariance_eq_sphericalEpsilon
#print axioms AFPBarrier.radialCovariance_eq_sphericalEpsilon
-- AFPBarrier/QEqualityCovariance.lean:56
#check AFPBarrier.sphericalEpsilon_eq_four_mul_Q_div_rate
#print axioms AFPBarrier.sphericalEpsilon_eq_four_mul_Q_div_rate
-- AFPBarrier/QEqualityCovariance.lean:79
#check AFPBarrier.normalizedTangent_centered_of_barycenter
#print axioms AFPBarrier.normalizedTangent_centered_of_barycenter
-- AFPBarrier/QEqualityCovariance.lean:121
#check AFPBarrier.normalizedTangentSecondMoment_trace_one
#print axioms AFPBarrier.normalizedTangentSecondMoment_trace_one
-- AFPBarrier/QEqualityCovariance.lean:148
#check AFPBarrier.weighted_centered_affine_product_sum
#print axioms AFPBarrier.weighted_centered_affine_product_sum
-- AFPBarrier/QEqualityCovariance.lean:182
#check AFPBarrier.qOne_covarianceEntry_decomposition
#print axioms AFPBarrier.qOne_covarianceEntry_decomposition
-- AFPBarrier/QEqualityCovariance.lean:222
#check AFPBarrier.jumpCovariance_eq_rate_mul_normalized
#print axioms AFPBarrier.jumpCovariance_eq_rate_mul_normalized
-- AFPBarrier/QEqualityCovariance.lean:238
#check AFPBarrier.qOne_jumpCovariance_decomposition
#print axioms AFPBarrier.qOne_jumpCovariance_decomposition
-- AFPBarrier/QEqualityCovariance.lean:280
#check AFPBarrier.qOne_covariance_axial_iff_tangentHalf
#print axioms AFPBarrier.qOne_covariance_axial_iff_tangentHalf
-- AFPBarrier/QEqualityCovariance.lean:308
#check AFPBarrier.oneShellSecondMoment_eq_rate_mul_normalized
#print axioms AFPBarrier.oneShellSecondMoment_eq_rate_mul_normalized
-- AFPBarrier/QEqualityCovariance.lean:324
#check AFPBarrier.normalizedTangentHalf_iff_d3_oneShellSecondMoment
#print axioms AFPBarrier.normalizedTangentHalf_iff_d3_oneShellSecondMoment
-- AFPBarrier/QEqualityCovariance.lean:357
#check AFPBarrier.qOne_residual_entry_algebra
#print axioms AFPBarrier.qOne_residual_entry_algebra
-- AFPBarrier/QEqualityCovariance.lean:369
#check AFPBarrier.sphereResidualMatrix_entry_of_trace_six
#print axioms AFPBarrier.sphereResidualMatrix_entry_of_trace_six
-- AFPBarrier/QEqualityCovariance.lean:392
#check AFPBarrier.qOne_sphereResidual_entry_decomposition
#print axioms AFPBarrier.qOne_sphereResidual_entry_decomposition
-- AFPBarrier/QEqualityCovariance.lean:474
#check AFPBarrier.weightedOctahedron_axis_axial_iff
#print axioms AFPBarrier.weightedOctahedron_axis_axial_iff
-- AFPBarrier/QEqualityCovariance.lean:490
#check AFPBarrier.weightedOctahedron_all_axes_axial_iff
#print axioms AFPBarrier.weightedOctahedron_all_axes_axial_iff
-- AFPBarrier/QuadraticCovariance.lean:41
#check AFPBarrier.jumpGenerator_sampledQuadratic
#print axioms AFPBarrier.jumpGenerator_sampledQuadratic
-- AFPBarrier/QuadraticCovariance.lean:90
#check AFPBarrier.sampledQuadratic_arbitraryTarget
#print axioms AFPBarrier.sampledQuadratic_arbitraryTarget
-- AFPBarrier/QuadraticCovariance.lean:108
#check AFPBarrier.sampledQuadratic_eigen_iff
#print axioms AFPBarrier.sampledQuadratic_eigen_iff
-- AFPBarrier/QuadraticCovariance.lean:132
#check AFPBarrier.weighted_sum_jumpGenerator_eq_zero_of_detailedBalance
#print axioms AFPBarrier.weighted_sum_jumpGenerator_eq_zero_of_detailedBalance
-- AFPBarrier/QuadraticCovariance.lean:152
#check AFPBarrier.detailedBalance_eigen_implies_weightedMean_zero
#print axioms AFPBarrier.detailedBalance_eigen_implies_weightedMean_zero
-- AFPBarrier/QuadraticCovariance.lean:181
#check AFPBarrier.sampledQuadratic_center_eq_weightedMean
#print axioms AFPBarrier.sampledQuadratic_center_eq_weightedMean
-- AFPBarrier/QuadraticCovariance.lean:225
#check AFPBarrier.sampledQuadratic_zeroTarget_center_independent
#print axioms AFPBarrier.sampledQuadratic_zeroTarget_center_independent
-- AFPBarrier/QuadraticEqualityGeometry.lean:29
#check AFPBarrier.increment_radial_tangent_decomposition
#print axioms AFPBarrier.increment_radial_tangent_decomposition
-- AFPBarrier/QuadraticEqualityGeometry.lean:38
#check AFPBarrier.projectedTangentIncrement_orthogonal
#print axioms AFPBarrier.projectedTangentIncrement_orthogonal
-- AFPBarrier/QuadraticEqualityGeometry.lean:58
#check AFPBarrier.projectedTangentIncrement_normSq
#print axioms AFPBarrier.projectedTangentIncrement_normSq
-- AFPBarrier/QuadraticEqualityGeometry.lean:88
#check AFPBarrier.equalityRemainderEntry_zero_iff_axialCovariance
#print axioms AFPBarrier.equalityRemainderEntry_zero_iff_axialCovariance
-- AFPBarrier/QuadraticEqualityGeometry.lean:109
#check AFPBarrier.oneShell_axialCovariance_iff_tangentSecondMoment
#print axioms AFPBarrier.oneShell_axialCovariance_iff_tangentSecondMoment
-- AFPBarrier/QuadraticEqualityGeometry.lean:144
#check AFPBarrier.oneShellSecondMoment_scaled
#print axioms AFPBarrier.oneShellSecondMoment_scaled
-- AFPBarrier/QuadraticEqualityGeometry.lean:158
#check AFPBarrier.normalizedTangentTightFrame_iff_oneShellSecondMoment
#print axioms AFPBarrier.normalizedTangentTightFrame_iff_oneShellSecondMoment
-- AFPBarrier/QuadraticEqualityGeometry.lean:193
#check AFPBarrier.oneShell_normalizedWeights_sum_one
#print axioms AFPBarrier.oneShell_normalizedWeights_sum_one
-- AFPBarrier/QuadraticEqualityGeometry.lean:210
#check AFPBarrier.scaledTangentTightFrame_iff_normalized
#print axioms AFPBarrier.scaledTangentTightFrame_iff_normalized
-- AFPBarrier/QuadraticEqualityGeometry.lean:260
#check AFPBarrier.scaledTangentTightFrame_iff_normalized_of_nonantipodal
#print axioms AFPBarrier.scaledTangentTightFrame_iff_normalized_of_nonantipodal
-- AFPBarrier/QuadraticEqualityGeometry.lean:282
#check AFPBarrier.quadraticEquality_rate_product
#print axioms AFPBarrier.quadraticEquality_rate_product
-- AFPBarrier/QuadraticFidelityConstruction.lean:34
#check AFPBarrier.construction_constant_reproduction
#print axioms AFPBarrier.construction_constant_reproduction
-- AFPBarrier/QuadraticFidelityConstruction.lean:41
#check AFPBarrier.construction_increment_decomposition
#print axioms AFPBarrier.construction_increment_decomposition
-- AFPBarrier/QuadraticFidelityConstruction.lean:53
#check AFPBarrier.tangentForce_zero_radialMass_exactForce
#print axioms AFPBarrier.tangentForce_zero_radialMass_exactForce
-- AFPBarrier/QuadraticFidelityConstruction.lean:88
#check AFPBarrier.tangentForce_zero_radialMass_hOne
#print axioms AFPBarrier.tangentForce_zero_radialMass_hOne
-- AFPBarrier/QuadraticFidelityConstruction.lean:105
#check AFPBarrier.sharedConductance_detailedBalance_entry
#print axioms AFPBarrier.sharedConductance_detailedBalance_entry
-- AFPBarrier/QuadraticFidelityConstruction.lean:118
#check AFPBarrier.unnormalizedMoment_div_mass_entry
#print axioms AFPBarrier.unnormalizedMoment_div_mass_entry
-- AFPBarrier/QuadraticFidelityConstruction.lean:126
#check AFPBarrier.unnormalizedMomentSum_div_mass_entry
#print axioms AFPBarrier.unnormalizedMomentSum_div_mass_entry
-- AFPBarrier/QuadraticFidelityConstruction.lean:141
#check AFPBarrier.constructionCorrection_closes
#print axioms AFPBarrier.constructionCorrection_closes
-- AFPBarrier/QuadraticFidelityConstruction.lean:151
#check AFPBarrier.constructionCorrection_force_zero
#print axioms AFPBarrier.constructionCorrection_force_zero
-- AFPBarrier/QuadraticFidelityConstruction.lean:167
#check AFPBarrier.fourPointConnector_firstMoment
#print axioms AFPBarrier.fourPointConnector_firstMoment
-- AFPBarrier/QuadraticFidelityConstruction.lean:185
#check AFPBarrier.fourPointConnector_cubicMoment
#print axioms AFPBarrier.fourPointConnector_cubicMoment
-- AFPBarrier/QuadraticFidelityConstruction.lean:203
#check AFPBarrier.fourPointConnector_weight_pos
#print axioms AFPBarrier.fourPointConnector_weight_pos
-- AFPBarrier/QuadraticFidelityConstruction.lean:210
#check AFPBarrier.chordMass_outgoingConductance_bound
#print axioms AFPBarrier.chordMass_outgoingConductance_bound
-- AFPBarrier/QuadraticFidelityConstruction.lean:231
#check AFPBarrier.chordMass_normalizedRate_bound
#print axioms AFPBarrier.chordMass_normalizedRate_bound
-- AFPBarrier/QuadraticFidelityConstruction.lean:245
#check AFPBarrier.regularPolygon_hOne_scalar_recurrence
#print axioms AFPBarrier.regularPolygon_hOne_scalar_recurrence
-- AFPBarrier/QuadraticFidelityConstruction.lean:260
#check AFPBarrier.regularPolygon_hTwo_scalar_residual
#print axioms AFPBarrier.regularPolygon_hTwo_scalar_residual
-- AFPBarrier/QuadraticFidelityConstruction.lean:281
#check AFPBarrier.regularPolygon_hTwo_scalar_eigenvalue
#print axioms AFPBarrier.regularPolygon_hTwo_scalar_eigenvalue
-- AFPBarrier/QuadraticFidelityFoundation.lean:49
#check AFPBarrier.weightedFrobeniusRowSynthesis_adjoint
#print axioms AFPBarrier.weightedFrobeniusRowSynthesis_adjoint
-- AFPBarrier/QuadraticFidelityFoundation.lean:85
#check AFPBarrier.weightedFrobeniusRowGram_pairing
#print axioms AFPBarrier.weightedFrobeniusRowGram_pairing
-- AFPBarrier/QuadraticFidelityFoundation.lean:96
#check AFPBarrier.weightedFrobeniusRowGram_quadratic
#print axioms AFPBarrier.weightedFrobeniusRowGram_quadratic
-- AFPBarrier/QuadraticFidelityFoundation.lean:113
#check AFPBarrier.sphereSamplingLinear_eq_frobeniusRowAnalysis
#print axioms AFPBarrier.sphereSamplingLinear_eq_frobeniusRowAnalysis
-- AFPBarrier/QuadraticFidelityFoundation.lean:139
#check AFPBarrier.sphereSamplingWeightedGram_pairing
#print axioms AFPBarrier.sphereSamplingWeightedGram_pairing
-- AFPBarrier/QuadraticFidelityFoundation.lean:153
#check AFPBarrier.sphereSamplingWeightedGram_quadratic
#print axioms AFPBarrier.sphereSamplingWeightedGram_quadratic
-- AFPBarrier/QuadraticFidelityFoundation.lean:170
#check AFPBarrier.sphereResidualWeightedGram_pairing
#print axioms AFPBarrier.sphereResidualWeightedGram_pairing
-- AFPBarrier/QuadraticFidelityFoundation.lean:187
#check AFPBarrier.sphereResidualWeightedGram_quadratic
#print axioms AFPBarrier.sphereResidualWeightedGram_quadratic
-- AFPBarrier/QuadraticFidelityFoundation.lean:206
#check AFPBarrier.frobeniusRowRemainder_pairing
#print axioms AFPBarrier.frobeniusRowRemainder_pairing
-- AFPBarrier/QuadraticFidelityFoundation.lean:225
#check AFPBarrier.matrixFrobeniusNormSq_rowRemainder
#print axioms AFPBarrier.matrixFrobeniusNormSq_rowRemainder
-- AFPBarrier/QuadraticFidelityFoundation.lean:260
#check AFPBarrier.quadraticTwoDefectRemainder_orthogonal
#print axioms AFPBarrier.quadraticTwoDefectRemainder_orthogonal
-- AFPBarrier/QuadraticFidelityFoundation.lean:274
#check AFPBarrier.quadraticTwoDefect_pythagorean
#print axioms AFPBarrier.quadraticTwoDefect_pythagorean
-- AFPBarrier/QuadraticFidelityFoundation.lean:290
#check AFPBarrier.exactLossSecondMoment_decomposition
#print axioms AFPBarrier.exactLossSecondMoment_decomposition
-- AFPBarrier/QuadraticFidelityLowerBound.lean:44
#check AFPBarrier.coordinateRowAnalysis_coordinateUnit
#print axioms AFPBarrier.coordinateRowAnalysis_coordinateUnit
-- AFPBarrier/QuadraticFidelityLowerBound.lean:53
#check AFPBarrier.weightedCoordinateTrace_le_of_energy_domination
#print axioms AFPBarrier.weightedCoordinateTrace_le_of_energy_domination
-- AFPBarrier/QuadraticFidelityLowerBound.lean:75
#check AFPBarrier.quadraticDefect_twoDefect_lower_sq
#print axioms AFPBarrier.quadraticDefect_twoDefect_lower_sq
-- AFPBarrier/QuadraticFidelityLowerBound.lean:97
#check AFPBarrier.quadraticDefect_rate_product_lower
#print axioms AFPBarrier.quadraticDefect_rate_product_lower
-- AFPBarrier/QuadraticFidelityLowerBound.lean:123
#check AFPBarrier.sTwo_quadraticDefect_rate_product_lower
#print axioms AFPBarrier.sTwo_quadraticDefect_rate_product_lower
-- AFPBarrier/QuadraticFidelityStability.lean:24
#check AFPBarrier.quadraticStability_slack_identity
#print axioms AFPBarrier.quadraticStability_slack_identity
-- AFPBarrier/QuadraticFidelityStability.lean:30
#check AFPBarrier.quadraticStability_total_sq_budget
#print axioms AFPBarrier.quadraticStability_total_sq_budget
-- AFPBarrier/QuadraticFidelityStability.lean:55
#check AFPBarrier.quadraticStability_total_linear_budget
#print axioms AFPBarrier.quadraticStability_total_linear_budget
-- AFPBarrier/QuadraticFidelityStability.lean:83
#check AFPBarrier.quadraticStability_component_sq_budget
#print axioms AFPBarrier.quadraticStability_component_sq_budget
-- AFPBarrier/QuadraticFidelityStability.lean:116
#check AFPBarrier.quadraticStability_pointwise_sq_budget
#print axioms AFPBarrier.quadraticStability_pointwise_sq_budget
-- AFPBarrier/QuadraticFidelityStability.lean:131
#check AFPBarrier.quadraticStability_pointwise_sq_budget_of_wmin
#print axioms AFPBarrier.quadraticStability_pointwise_sq_budget_of_wmin
-- AFPBarrier/QuadraticFidelityStability.lean:154
#check AFPBarrier.quadraticStability_badVertexMass
#print axioms AFPBarrier.quadraticStability_badVertexMass
-- AFPBarrier/QuadraticFidelityStability.lean:179
#check AFPBarrier.quadraticStability_badVertexMass_sharp
#print axioms AFPBarrier.quadraticStability_badVertexMass_sharp
-- AFPBarrier/QuadraticFidelityStability.lean:209
#check AFPBarrier.quadraticStability_pointwise_full_budget
#print axioms AFPBarrier.quadraticStability_pointwise_full_budget
-- AFPBarrier/QuadraticFidelityStability.lean:229
#check AFPBarrier.quadraticStability_tensor_budget
#print axioms AFPBarrier.quadraticStability_tensor_budget
-- AFPBarrier/QuadraticFidelityStability.lean:261
#check AFPBarrier.quadraticStability_tensor_rate_bound
#print axioms AFPBarrier.quadraticStability_tensor_rate_bound
-- AFPBarrier/QuadraticFidelityStability.lean:288
#check AFPBarrier.quadraticStability_scaledVariance_sq_budget
#print axioms AFPBarrier.quadraticStability_scaledVariance_sq_budget
-- AFPBarrier/QuadraticFidelityStability.lean:307
#check AFPBarrier.quadraticStability_master_square_consequences
#print axioms AFPBarrier.quadraticStability_master_square_consequences
-- AFPBarrier/QuadraticFidelityStability.lean:330
#check AFPBarrier.quadraticStability_mean_le_delta
#print axioms AFPBarrier.quadraticStability_mean_le_delta
-- AFPBarrier/QuadraticFidelityStability.lean:347
#check AFPBarrier.quadraticStability_weightedMean_le_delta
#print axioms AFPBarrier.quadraticStability_weightedMean_le_delta
-- AFPBarrier/QuadraticSampling.lean:41
#check AFPBarrier.sampledResidual_factorization
#print axioms AFPBarrier.sampledResidual_factorization
-- AFPBarrier/QuadraticSampling.lean:47
#check AFPBarrier.samplingKernel_subset_formExact
#print axioms AFPBarrier.samplingKernel_subset_formExact
-- AFPBarrier/QuadraticSampling.lean:59
#check AFPBarrier.sampledExact_iff_range_inter_targetKernel
#print axioms AFPBarrier.sampledExact_iff_range_inter_targetKernel
-- AFPBarrier/QuadraticSampling.lean:83
#check AFPBarrier.linear_samplingKernel_le_residualKernel
#print axioms AFPBarrier.linear_samplingKernel_le_residualKernel
-- AFPBarrier/QuadraticSampling.lean:91
#check AFPBarrier.linearSampledResidual_finrank_le_sampling
#print axioms AFPBarrier.linearSampledResidual_finrank_le_sampling
-- AFPBarrier/QuadraticSampling.lean:112
#check AFPBarrier.linearSampledExactRange_eq_range_inf_targetKernel
#print axioms AFPBarrier.linearSampledExactRange_eq_range_inf_targetKernel
-- AFPBarrier/QuadraticSampling.lean:126
#check AFPBarrier.linearSampledExactRange_finrank_add_samplingKernel
#print axioms AFPBarrier.linearSampledExactRange_finrank_add_samplingKernel
-- AFPBarrier/QuadraticSampling.lean:146
#check AFPBarrier.linearSampledExactRange_finrank_eq_formExact_sub_samplingKernel
#print axioms AFPBarrier.linearSampledExactRange_finrank_eq_formExact_sub_samplingKernel
-- AFPBarrier/QuadraticSampling.lean:158
#check AFPBarrier.linearSampledExactRange_finrank_eq_samplingRank_sub_residualRank
#print axioms AFPBarrier.linearSampledExactRange_finrank_eq_samplingRank_sub_residualRank
-- AFPBarrier/QuadraticSphereResidual.lean:42
#check AFPBarrier.matrixFrobeniusPairing_eq_trace_mul_of_isSymm_right
#print axioms AFPBarrier.matrixFrobeniusPairing_eq_trace_mul_of_isSymm_right
-- AFPBarrier/QuadraticSphereResidual.lean:74
#check AFPBarrier.matrixFrobeniusPairing_traceFreeProjection
#print axioms AFPBarrier.matrixFrobeniusPairing_traceFreeProjection
-- AFPBarrier/QuadraticSphereResidual.lean:104
#check AFPBarrier.trace_sphereResidualMatrix_eq_zero
#print axioms AFPBarrier.trace_sphereResidualMatrix_eq_zero
-- AFPBarrier/QuadraticSphereResidual.lean:131
#check AFPBarrier.sphereResidualMatrix_isSymm
#print axioms AFPBarrier.sphereResidualMatrix_isSymm
-- AFPBarrier/QuadraticSphereResidual.lean:158
#check AFPBarrier.sphereCovarianceAddOuter_isSymm
#print axioms AFPBarrier.sphereCovarianceAddOuter_isSymm
-- AFPBarrier/QuadraticSphereResidual.lean:249
#check AFPBarrier.matrixFrobeniusPairing_covariance_add_outer
#print axioms AFPBarrier.matrixFrobeniusPairing_covariance_add_outer
-- AFPBarrier/QuadraticSphereResidual.lean:283
#check AFPBarrier.sphereResidual_factorization
#print axioms AFPBarrier.sphereResidual_factorization
-- AFPBarrier/QuadraticSphereResidual.lean:306
#check AFPBarrier.matrixFrobeniusPairing_sphereResidualMatrix_eq_trace
#print axioms AFPBarrier.matrixFrobeniusPairing_sphereResidualMatrix_eq_trace
-- AFPBarrier/QuadraticSphereResidual.lean:322
#check AFPBarrier.sphereResidual_factorization_trace
#print axioms AFPBarrier.sphereResidual_factorization_trace
-- AFPBarrier/QuadraticSphereResidual.lean:376
#check AFPBarrier.sphereFormExact_eq_residualOrthogonal
#print axioms AFPBarrier.sphereFormExact_eq_residualOrthogonal
-- AFPBarrier/QuadraticSphereResidual.lean:398
#check AFPBarrier.sphereSamplingKernel_le_formExact
#print axioms AFPBarrier.sphereSamplingKernel_le_formExact
-- AFPBarrier/QuadraticSphereResidual.lean:407
#check AFPBarrier.sphereSampledExact_eq_range_inf_targetKernel
#print axioms AFPBarrier.sphereSampledExact_eq_range_inf_targetKernel
-- AFPBarrier/QuadraticSphereResidual.lean:420
#check AFPBarrier.sphereSampledExact_finrank_eq_form_sub_alias
#print axioms AFPBarrier.sphereSampledExact_finrank_eq_form_sub_alias
-- AFPBarrier/QuadraticSphereResidual.lean:432
#check AFPBarrier.sphereSampledExact_finrank_eq_samplingRank_sub_residualRank
#print axioms AFPBarrier.sphereSampledExact_finrank_eq_samplingRank_sub_residualRank
-- AFPBarrier/Quantitative.lean:19
#check AFPBarrier.peakDefect_eq_carreDuChamp
#print axioms AFPBarrier.peakDefect_eq_carreDuChamp
-- AFPBarrier/Quantitative.lean:33
#check AFPBarrier.peakDefect_nonneg
#print axioms AFPBarrier.peakDefect_nonneg
-- AFPBarrier/Quantitative.lean:45
#check AFPBarrier.eigenvalue_sq_le_rate_mul_peakDefect
#print axioms AFPBarrier.eigenvalue_sq_le_rate_mul_peakDefect
-- AFPBarrier/Quantitative.lean:62
#check AFPBarrier.peakDefect_pos
#print axioms AFPBarrier.peakDefect_pos
-- AFPBarrier/Quantitative.lean:82
#check AFPBarrier.peakDefect_lower_bound
#print axioms AFPBarrier.peakDefect_lower_bound
-- AFPBarrier/QuantitativeExactLocal.lean:24
#check AFPBarrier.uniformDependenceMixture_sum
#print axioms AFPBarrier.uniformDependenceMixture_sum
-- AFPBarrier/QuantitativeExactLocal.lean:40
#check AFPBarrier.uniformDependenceMixture_lower
#print axioms AFPBarrier.uniformDependenceMixture_lower
-- AFPBarrier/QuantitativeExactLocal.lean:52
#check AFPBarrier.normalizedWeightedSum_bounds
#print axioms AFPBarrier.normalizedWeightedSum_bounds
-- AFPBarrier/QuantitativeExactLocal.lean:79
#check AFPBarrier.normalizedAngularScale_bounds
#print axioms AFPBarrier.normalizedAngularScale_bounds
-- AFPBarrier/QuantitativeExactLocal.lean:92
#check AFPBarrier.exactLocalRowRate_sum_bounds
#print axioms AFPBarrier.exactLocalRowRate_sum_bounds
-- AFPBarrier/QuantitativeExactLocal.lean:124
#check AFPBarrier.exactLocalRowRate_twoFactor_bounds
#print axioms AFPBarrier.exactLocalRowRate_twoFactor_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:28
#check AFPBarrier.abs_sub_one_le_of_sq_le_delta_sq
#print axioms AFPBarrier.abs_sub_one_le_of_sq_le_delta_sq
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:39
#check AFPBarrier.pointwise_delta_bound
#print axioms AFPBarrier.pointwise_delta_bound
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:61
#check AFPBarrier.sphericalQ_pointwise_delta_bound
#print axioms AFPBarrier.sphericalQ_pointwise_delta_bound
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:107
#check AFPBarrier.normalized_scale_interval_of_abs
#print axioms AFPBarrier.normalized_scale_interval_of_abs
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:115
#check AFPBarrier.one_le_qDelta
#print axioms AFPBarrier.one_le_qDelta
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:125
#check AFPBarrier.normalized_scale_qDelta_cross_bounds
#print axioms AFPBarrier.normalized_scale_qDelta_cross_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:167
#check AFPBarrier.adjacent_rate_cross_bounds
#print axioms AFPBarrier.adjacent_rate_cross_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:192
#check AFPBarrier.adjacent_rate_ratio_bounds
#print axioms AFPBarrier.adjacent_rate_ratio_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:215
#check AFPBarrier.adjacent_rate_relative_error_bound
#print axioms AFPBarrier.adjacent_rate_relative_error_bound
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:253
#check AFPBarrier.adjacent_rate_qDelta_cross_bounds
#print axioms AFPBarrier.adjacent_rate_qDelta_cross_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:288
#check AFPBarrier.incident_loss_cross_bounds
#print axioms AFPBarrier.incident_loss_cross_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:336
#check AFPBarrier.incident_loss_ratio_bounds
#print axioms AFPBarrier.incident_loss_ratio_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:391
#check AFPBarrier.path_rate_cross_bounds
#print axioms AFPBarrier.path_rate_cross_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:424
#check AFPBarrier.path_rate_ratio_bounds
#print axioms AFPBarrier.path_rate_ratio_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:447
#check AFPBarrier.path_loss_ratio_bounds
#print axioms AFPBarrier.path_loss_ratio_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:519
#check AFPBarrier.abs_log_rate_sub_le_of_cross_bounds
#print axioms AFPBarrier.abs_log_rate_sub_le_of_cross_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:537
#check AFPBarrier.adjacent_log_rate_bound
#print axioms AFPBarrier.adjacent_log_rate_bound
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:555
#check AFPBarrier.path_log_rate_bound
#print axioms AFPBarrier.path_log_rate_bound
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:582
#check AFPBarrier.abs_log_normalized_scale_le_hDelta
#print axioms AFPBarrier.abs_log_normalized_scale_le_hDelta
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:614
#check AFPBarrier.reference_loss_log_bound
#print axioms AFPBarrier.reference_loss_log_bound
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:662
#check AFPBarrier.diameter_log_rate_bound
#print axioms AFPBarrier.diameter_log_rate_bound
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:681
#check AFPBarrier.pow_le_pow_of_one_le_of_nat_le
#print axioms AFPBarrier.pow_le_pow_of_one_le_of_nat_le
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:692
#check AFPBarrier.diameter_rate_ratio_bounds
#print axioms AFPBarrier.diameter_rate_ratio_bounds
-- AFPBarrier/QuantitativeGlobalNearRigidity.lean:726
#check AFPBarrier.radial_covariance_error_bounds
#print axioms AFPBarrier.radial_covariance_error_bounds
-- AFPBarrier/QuantitativeSphericalFeasibility.lean:24
#check AFPBarrier.sphericalOutgoingRate_nonneg
#print axioms AFPBarrier.sphericalOutgoingRate_nonneg
-- AFPBarrier/QuantitativeSphericalFeasibility.lean:32
#check AFPBarrier.normalBalance_lossUpper_crossBound
#print axioms AFPBarrier.normalBalance_lossUpper_crossBound
-- AFPBarrier/QuantitativeSphericalFeasibility.lean:57
#check AFPBarrier.normalBalance_lossLower_crossBound
#print axioms AFPBarrier.normalBalance_lossLower_crossBound
-- AFPBarrier/QuantitativeSphericalFeasibility.lean:81
#check AFPBarrier.normalBalance_outgoingRate_lower
#print axioms AFPBarrier.normalBalance_outgoingRate_lower
-- AFPBarrier/QuantitativeSphericalFeasibility.lean:94
#check AFPBarrier.normalBalance_outgoingRate_upper
#print axioms AFPBarrier.normalBalance_outgoingRate_upper
-- AFPBarrier/QuasiUniformLossBounds.lean:30
#check AFPBarrier.lossMoment_eq_eigenvalue
#print axioms AFPBarrier.lossMoment_eq_eigenvalue
-- AFPBarrier/QuasiUniformLossBounds.lean:45
#check AFPBarrier.lossMin_mul_rate_le_eigenvalue
#print axioms AFPBarrier.lossMin_mul_rate_le_eigenvalue
-- AFPBarrier/QuasiUniformLossBounds.lean:62
#check AFPBarrier.eigenvalue_le_lossMax_mul_rate
#print axioms AFPBarrier.eigenvalue_le_lossMax_mul_rate
-- AFPBarrier/QuasiUniformLossBounds.lean:79
#check AFPBarrier.lossMin_mul_eigenvalue_le_peakDefect
#print axioms AFPBarrier.lossMin_mul_eigenvalue_le_peakDefect
-- AFPBarrier/QuasiUniformLossBounds.lean:104
#check AFPBarrier.peakDefect_le_lossMax_mul_eigenvalue
#print axioms AFPBarrier.peakDefect_le_lossMax_mul_eigenvalue
-- AFPBarrier/QuasiUniformLossBounds.lean:130
#check AFPBarrier.quasiUniform_loss_rate_defect_bounds
#print axioms AFPBarrier.quasiUniform_loss_rate_defect_bounds
-- AFPBarrier/QuasiUniformLossBounds.lean:151
#check AFPBarrier.eigenvalue_div_lossMax_le_rate
#print axioms AFPBarrier.eigenvalue_div_lossMax_le_rate
-- AFPBarrier/QuasiUniformLossBounds.lean:163
#check AFPBarrier.rate_le_eigenvalue_div_lossMin
#print axioms AFPBarrier.rate_le_eigenvalue_div_lossMin
-- AFPBarrier/QuasiUniformLossBounds.lean:177
#check AFPBarrier.quadraticLoss_rate_defect_bounds
#print axioms AFPBarrier.quadraticLoss_rate_defect_bounds
-- AFPBarrier/ReversibleConductance.lean:29
#check AFPBarrier.conductanceRate_nonneg
#print axioms AFPBarrier.conductanceRate_nonneg
-- AFPBarrier/ReversibleConductance.lean:38
#check AFPBarrier.conductanceRate_detailedBalance
#print axioms AFPBarrier.conductanceRate_detailedBalance
-- AFPBarrier/ReversibleConductance.lean:53
#check AFPBarrier.weightedAdjointRate_conductanceRate_eq
#print axioms AFPBarrier.weightedAdjointRate_conductanceRate_eq
-- AFPBarrier/ReversibleConductance.lean:68
#check AFPBarrier.weight_mul_jumpGenerator_conductanceRate
#print axioms AFPBarrier.weight_mul_jumpGenerator_conductanceRate
-- AFPBarrier/ReversibleConductance.lean:93
#check AFPBarrier.weighted_sum_jumpGenerator_conductanceRate_eq_zero
#print axioms AFPBarrier.weighted_sum_jumpGenerator_conductanceRate_eq_zero
-- AFPBarrier/ReversibleConductance.lean:140
#check AFPBarrier.conductance_eigen_implies_weightedMean_zero
#print axioms AFPBarrier.conductance_eigen_implies_weightedMean_zero
-- AFPBarrier/ReversibleConductance.lean:171
#check AFPBarrier.no_exact_conductance_linear_and_square_at_peak
#print axioms AFPBarrier.no_exact_conductance_linear_and_square_at_peak
-- AFPBarrier/ScalingCompatibility.lean:22
#check AFPBarrier.conductanceRate_common_scale
#print axioms AFPBarrier.conductanceRate_common_scale
-- AFPBarrier/ScalingCompatibility.lean:32
#check AFPBarrier.jumpGenerator_conductance_common_scale
#print axioms AFPBarrier.jumpGenerator_conductance_common_scale
-- AFPBarrier/ScalingCompatibility.lean:45
#check AFPBarrier.equilibrium_common_scale
#print axioms AFPBarrier.equilibrium_common_scale
-- AFPBarrier/ScalingCompatibility.lean:67
#check AFPBarrier.geometric_pair_transfers_to_scaled_quadrature
#print axioms AFPBarrier.geometric_pair_transfers_to_scaled_quadrature
-- AFPBarrier/SharedEdgeEquilibrium.lean:35
#check AFPBarrier.sharedEdgeColumn_swap
#print axioms AFPBarrier.sharedEdgeColumn_swap
-- AFPBarrier/SharedEdgeEquilibrium.lean:45
#check AFPBarrier.sharedEdgeColumn_nodeSum_zero
#print axioms AFPBarrier.sharedEdgeColumn_nodeSum_zero
-- AFPBarrier/SharedEdgeEquilibrium.lean:61
#check AFPBarrier.sharedEdgeApply_nodeSum_zero
#print axioms AFPBarrier.sharedEdgeApply_nodeSum_zero
-- AFPBarrier/SharedEdgeEquilibrium.lean:73
#check AFPBarrier.sharedEdge_equilibrium_implies_rhs_nodeSum_zero
#print axioms AFPBarrier.sharedEdge_equilibrium_implies_rhs_nodeSum_zero
-- AFPBarrier/SharedEdgeEquilibrium.lean:89
#check AFPBarrier.sharedEdge_equilibrium_implies_weightedCentering
#print axioms AFPBarrier.sharedEdge_equilibrium_implies_weightedCentering
-- AFPBarrier/SharedEdgeEquilibrium.lean:125
#check AFPBarrier.squareLocalRate_nonneg
#print axioms AFPBarrier.squareLocalRate_nonneg
-- AFPBarrier/SharedEdgeEquilibrium.lean:131
#check AFPBarrier.squareLocalRate_permitted_pos
#print axioms AFPBarrier.squareLocalRate_permitted_pos
-- AFPBarrier/SharedEdgeEquilibrium.lean:142
#check AFPBarrier.squareLocalRate_coordinate_exact
#print axioms AFPBarrier.squareLocalRate_coordinate_exact
-- AFPBarrier/SharedEdgeEquilibrium.lean:149
#check AFPBarrier.squareWeight_pos
#print axioms AFPBarrier.squareWeight_pos
-- AFPBarrier/SharedEdgeEquilibrium.lean:152
#check AFPBarrier.square_weighted_centering
#print axioms AFPBarrier.square_weighted_centering
-- AFPBarrier/SharedEdgeEquilibrium.lean:168
#check AFPBarrier.squareBalanceMatrix_columnSum_zero
#print axioms AFPBarrier.squareBalanceMatrix_columnSum_zero
-- AFPBarrier/SharedEdgeEquilibrium.lean:181
#check AFPBarrier.squareDual_transpose_zero
#print axioms AFPBarrier.squareDual_transpose_zero
-- AFPBarrier/SharedEdgeEquilibrium.lean:188
#check AFPBarrier.squareDual_work
#print axioms AFPBarrier.squareDual_work
-- AFPBarrier/SharedEdgeEquilibrium.lean:194
#check AFPBarrier.square_sharedEdge_infeasible
#print axioms AFPBarrier.square_sharedEdge_infeasible
-- AFPBarrier/SharpProductBarriers.lean:35
#check AFPBarrier.squarePolarQualityFromStep_formula
#print axioms AFPBarrier.squarePolarQualityFromStep_formula
-- AFPBarrier/SharpProductBarriers.lean:49
#check AFPBarrier.squarePolar_rates_forced
#print axioms AFPBarrier.squarePolar_rates_forced
-- AFPBarrier/SharpProductBarriers.lean:76
#check AFPBarrier.squarePolar_totalRate_forced
#print axioms AFPBarrier.squarePolar_totalRate_forced
-- AFPBarrier/SharpProductBarriers.lean:96
#check AFPBarrier.squarePolar_forced_quartic_lower
#print axioms AFPBarrier.squarePolar_forced_quartic_lower
-- AFPBarrier/SharpProductBarriers.lean:113
#check AFPBarrier.cscSquaredTruncation_rate_identity
#print axioms AFPBarrier.cscSquaredTruncation_rate_identity
-- AFPBarrier/SharpProductBarriers.lean:124
#check AFPBarrier.squarePolarRateMainStep_grid
#print axioms AFPBarrier.squarePolarRateMainStep_grid
-- AFPBarrier/SharpProductBarriers.lean:139
#check AFPBarrier.squarePolarQualityMainStep_grid
#print axioms AFPBarrier.squarePolarQualityMainStep_grid
-- AFPBarrier/SharpProductBarriers.lean:149
#check AFPBarrier.universal_rate_lower_of_defect_upper
#print axioms AFPBarrier.universal_rate_lower_of_defect_upper
-- AFPBarrier/SharpProductBarriers.lean:164
#check AFPBarrier.finiteExtremal_defect_lower
#print axioms AFPBarrier.finiteExtremal_defect_lower
-- AFPBarrier/SharpProductBarriers.lean:181
#check AFPBarrier.projectiveQuality_from_fixedMoment
#print axioms AFPBarrier.projectiveQuality_from_fixedMoment
-- AFPBarrier/SharpProductBarriers.lean:192
#check AFPBarrier.twoLossWeightedQuality_sub_one
#print axioms AFPBarrier.twoLossWeightedQuality_sub_one
-- AFPBarrier/SharpProductBarriers.lean:204
#check AFPBarrier.twoLossQuality_sub_one
#print axioms AFPBarrier.twoLossQuality_sub_one
-- AFPBarrier/SharpProductBarriers.lean:213
#check AFPBarrier.biregular_interRing_incidence
#print axioms AFPBarrier.biregular_interRing_incidence
-- AFPBarrier/SharpProductBarriers.lean:221
#check AFPBarrier.perfectMatching_ringCounts_eq
#print axioms AFPBarrier.perfectMatching_ringCounts_eq
-- AFPBarrier/SpatialUpwindTransport.lean:37
#check AFPBarrier.spatialUpwindEulerCell_eq_positive_form
#print axioms AFPBarrier.spatialUpwindEulerCell_eq_positive_form
-- AFPBarrier/SpatialUpwindTransport.lean:73
#check AFPBarrier.spatialUpwindEulerCell_nonneg
#print axioms AFPBarrier.spatialUpwindEulerCell_nonneg
-- AFPBarrier/SpatialUpwindTransport.lean:104
#check AFPBarrier.spatialUpwindEulerCell_unitAt
#print axioms AFPBarrier.spatialUpwindEulerCell_unitAt
-- AFPBarrier/SpatialUpwindTransport.lean:120
#check AFPBarrier.spatialUpwindEulerCell_unitAt_neg_of_cfl_violation
#print axioms AFPBarrier.spatialUpwindEulerCell_unitAt_neg_of_cfl_violation
-- AFPBarrier/SpectralProductAlgebra.lean:26
#check AFPBarrier.jumpGenerator_finset_sum
#print axioms AFPBarrier.jumpGenerator_finset_sum
-- AFPBarrier/SpectralProductAlgebra.lean:46
#check AFPBarrier.jumpGenerator_const_mul
#print axioms AFPBarrier.jumpGenerator_const_mul
-- AFPBarrier/SpectralProductAlgebra.lean:61
#check AFPBarrier.jumpGenerator_product_identity
#print axioms AFPBarrier.jumpGenerator_product_identity
-- AFPBarrier/SpectralProductAlgebra.lean:85
#check AFPBarrier.spectralProduct_arbitraryTarget
#print axioms AFPBarrier.spectralProduct_arbitraryTarget
-- AFPBarrier/SpectralProductAlgebra.lean:101
#check AFPBarrier.spectralProduct_resonance_iff
#print axioms AFPBarrier.spectralProduct_resonance_iff
-- AFPBarrier/SpectralProductAlgebra.lean:123
#check AFPBarrier.two_mixedCarreDuChamp_self
#print axioms AFPBarrier.two_mixedCarreDuChamp_self
-- AFPBarrier/SpectralProductAlgebra.lean:140
#check AFPBarrier.spectralSquare_resonance_iff
#print axioms AFPBarrier.spectralSquare_resonance_iff
-- AFPBarrier/SpectralSamplingObstruction.lean:27
#check AFPBarrier.spectralSampledSpaces_iSupIndep
#print axioms AFPBarrier.spectralSampledSpaces_iSupIndep
-- AFPBarrier/SpectralSamplingObstruction.lean:35
#check AFPBarrier.spectralSampledSpaces_pairwise_disjoint
#print axioms AFPBarrier.spectralSampledSpaces_pairwise_disjoint
-- AFPBarrier/SpectralSamplingObstruction.lean:43
#check AFPBarrier.spectralSampledSpaces_finrank_sum_le
#print axioms AFPBarrier.spectralSampledSpaces_finrank_sum_le
-- AFPBarrier/SpectralSamplingObstruction.lean:59
#check AFPBarrier.spectralSampledFunctions_finrank_sum_le
#print axioms AFPBarrier.spectralSampledFunctions_finrank_sum_le
-- AFPBarrier/SpectralSamplingObstruction.lean:75
#check AFPBarrier.sphericalEigenvalue_injective
#print axioms AFPBarrier.sphericalEigenvalue_injective
-- AFPBarrier/SpectralSamplingObstruction.lean:110
#check AFPBarrier.harmonicSampledSpaces_iSupIndep
#print axioms AFPBarrier.harmonicSampledSpaces_iSupIndep
-- AFPBarrier/SpectralSamplingObstruction.lean:127
#check AFPBarrier.sphericalEigenvalue_dimension_one_collision
#print axioms AFPBarrier.sphericalEigenvalue_dimension_one_collision
-- AFPBarrier/SpectralSamplingObstruction.lean:131
#check AFPBarrier.sphericalEigenvalue_dimension_one_not_injective
#print axioms AFPBarrier.sphericalEigenvalue_dimension_one_not_injective
-- AFPBarrier/SpectralSamplingObstruction.lean:153
#check AFPBarrier.internalScalarOperator_apply_of_mem
#print axioms AFPBarrier.internalScalarOperator_apply_of_mem
-- AFPBarrier/SpectralSamplingObstruction.lean:193
#check AFPBarrier.internalScalarOperator_eq_zero_of_mem_zeroSummand
#print axioms AFPBarrier.internalScalarOperator_eq_zero_of_mem_zeroSummand
-- AFPBarrier/SpectralSamplingObstruction.lean:204
#check AFPBarrier.internalScalarOperator_constants_eq_zero
#print axioms AFPBarrier.internalScalarOperator_constants_eq_zero
-- AFPBarrier/SphereSpecialization.lean:18
#check AFPBarrier.no_exact_S2_degree_two_at_peak
#print axioms AFPBarrier.no_exact_S2_degree_two_at_peak
-- AFPBarrier/SphereSpecialization.lean:34
#check AFPBarrier.S2_four_le_rate_mul_defect
#print axioms AFPBarrier.S2_four_le_rate_mul_defect
-- AFPBarrier/SphericalFeasibilityAlgebra.lean:28
#check AFPBarrier.tangentNormalScale_pos
#print axioms AFPBarrier.tangentNormalScale_pos
-- AFPBarrier/SphericalFeasibilityAlgebra.lean:47
#check AFPBarrier.commonScale_eq_two_div
#print axioms AFPBarrier.commonScale_eq_two_div
-- AFPBarrier/SphericalFeasibilityAlgebra.lean:54
#check AFPBarrier.commonScale_pos
#print axioms AFPBarrier.commonScale_pos
-- AFPBarrier/SphericalFeasibilityAlgebra.lean:62
#check AFPBarrier.scaledSphericalRowRate_eq_commonScale
#print axioms AFPBarrier.scaledSphericalRowRate_eq_commonScale
-- AFPBarrier/SphericalFeasibilityAlgebra.lean:78
#check AFPBarrier.mixedNormalBudget_identity
#print axioms AFPBarrier.mixedNormalBudget_identity
-- AFPBarrier/SphericalFeasibilityAlgebra.lean:84
#check AFPBarrier.antipodalTotalRate_eq_of_mixedNormalBudget
#print axioms AFPBarrier.antipodalTotalRate_eq_of_mixedNormalBudget
-- AFPBarrier/SphericalFeasibilityAlgebra.lean:92
#check AFPBarrier.antipodalTotalRate_nonneg_iff
#print axioms AFPBarrier.antipodalTotalRate_nonneg_iff
-- AFPBarrier/SphericalFeasibilityAlgebra.lean:99
#check AFPBarrier.antipodalTotalRate_pos_iff
#print axioms AFPBarrier.antipodalTotalRate_pos_iff
-- AFPBarrier/SphericalFeasibilityAlgebra.lean:106
#check AFPBarrier.antipodalOnly_normalBalance_iff
#print axioms AFPBarrier.antipodalOnly_normalBalance_iff
-- AFPBarrier/SphericalNetScaling.lean:37
#check AFPBarrier.sphericalLoss_eq_two_sin_sq_half
#print axioms AFPBarrier.sphericalLoss_eq_two_sin_sq_half
-- AFPBarrier/SphericalNetScaling.lean:47
#check AFPBarrier.sphericalLoss_lower_quadratic
#print axioms AFPBarrier.sphericalLoss_lower_quadratic
-- AFPBarrier/SphericalNetScaling.lean:68
#check AFPBarrier.sphericalLoss_two_mul_upper
#print axioms AFPBarrier.sphericalLoss_two_mul_upper
-- AFPBarrier/SphericalNetScaling.lean:76
#check AFPBarrier.sphericalLoss_between_of_angle_window
#print axioms AFPBarrier.sphericalLoss_between_of_angle_window
-- AFPBarrier/SphericalNetScaling.lean:99
#check AFPBarrier.sphericalNet_peak_rate_defect_bounds
#print axioms AFPBarrier.sphericalNet_peak_rate_defect_bounds
-- AFPBarrier/SphericalNetScaling.lean:130
#check AFPBarrier.sphericalNet_peak_rate_defect_bounds_mul
#print axioms AFPBarrier.sphericalNet_peak_rate_defect_bounds_mul
-- AFPBarrier/SphericalQEqualityRigidity.lean:35
#check AFPBarrier.sphericalChordLoss_symmetric
#print axioms AFPBarrier.sphericalChordLoss_symmetric
-- AFPBarrier/SphericalQEqualityRigidity.lean:48
#check AFPBarrier.jumpGenerator_sphericalPairing
#print axioms AFPBarrier.jumpGenerator_sphericalPairing
-- AFPBarrier/SphericalQEqualityRigidity.lean:78
#check AFPBarrier.coordinateEigenmap_lossMoment_two
#print axioms AFPBarrier.coordinateEigenmap_lossMoment_two
-- AFPBarrier/SphericalQEqualityRigidity.lean:97
#check AFPBarrier.normalizedOmega_barycenter_of_coordinateEigenmap
#print axioms AFPBarrier.normalizedOmega_barycenter_of_coordinateEigenmap
-- AFPBarrier/SphericalQEqualityRigidity.lean:163
#check AFPBarrier.jumpRate_pos_of_lossMoment_two
#print axioms AFPBarrier.jumpRate_pos_of_lossMoment_two
-- AFPBarrier/SphericalQEqualityRigidity.lean:188
#check AFPBarrier.normalizedEdgeWeight_sum_one
#print axioms AFPBarrier.normalizedEdgeWeight_sum_one
-- AFPBarrier/SphericalQEqualityRigidity.lean:197
#check AFPBarrier.normalizedLossScale_mean_one
#print axioms AFPBarrier.normalizedLossScale_mean_one
-- AFPBarrier/SphericalQEqualityRigidity.lean:217
#check AFPBarrier.normalizedLossScale_secondMoment
#print axioms AFPBarrier.normalizedLossScale_secondMoment
-- AFPBarrier/SphericalQEqualityRigidity.lean:243
#check AFPBarrier.weightedSecondMoment_sub_one_eq_variance
#print axioms AFPBarrier.weightedSecondMoment_sub_one_eq_variance
-- AFPBarrier/SphericalQEqualityRigidity.lean:265
#check AFPBarrier.sphericalQ_sub_one_eq_normalizedLossVariance
#print axioms AFPBarrier.sphericalQ_sub_one_eq_normalizedLossVariance
-- AFPBarrier/SphericalQEqualityRigidity.lean:286
#check AFPBarrier.one_le_sphericalQAt
#print axioms AFPBarrier.one_le_sphericalQAt
-- AFPBarrier/SphericalQEqualityRigidity.lean:305
#check AFPBarrier.sphericalQ_eq_one_active_loss
#print axioms AFPBarrier.sphericalQ_eq_one_active_loss
-- AFPBarrier/SphericalQEqualityRigidity.lean:343
#check AFPBarrier.active_symmetric_of_shared_conductance
#print axioms AFPBarrier.active_symmetric_of_shared_conductance
-- AFPBarrier/SphericalQEqualityRigidity.lean:361
#check AFPBarrier.connected_spherical_active_loss_rigidity
#print axioms AFPBarrier.connected_spherical_active_loss_rigidity
-- AFPBarrier/SphericalQEqualityRigidity.lean:382
#check AFPBarrier.finite_spherical_qOne_global_rigidity
#print axioms AFPBarrier.finite_spherical_qOne_global_rigidity
